### DISCUSSION TITLE
Multilingual Support

### DISCUSSION THREAD

**Discussion by hng12** [adityatelange/hugo-PaperMod#1066] [Q&A]
How can I make my website multilingual? Could someone please point me in the right direction?

**Comment by RoneoOrg** [comment]
Quick notes, here is my setup for [a website based on Papermod](https://roneo.org/en/) available both in french and english.

Note that
- French is the default language here, 
- I use [translation by filename](https://gohugo.io/content-management/multilingual/#translation-by-filename)
- my config is split in [multiple files](https://gohugo.io/getting-started/configuration/#configuration-directory) for clarity

So,

in `config/_default/config.yml`

```
DefaultContentLanguage: "fr"
defaultContentLanguageInSubdir: false
```

in `config/_default/languages.yml`


```

  en:
      languageName: "English"
      weight: 2
      taxonomies:
        tag: tags
        series: series
      menu:
        main:
          - identifier: search
            name: Search
            url: search/
            weight: 10
          - identifier: contact
            name: Contact
            url: /contact/
            weight: 20
          - identifier: tags
            name: Tags
            url: /tags/
            weight: 30


  fr:
      languageName: "Français"
      languageAltTitle: French
      taxonomies:
        tag: tags
        series: series
      weight: 1
      homeInfoParams:
        Title: "Roneo.org"
        Content: >
            ### Notes à propos de **Linux, Git, Hugo** et la **Jamstack**

  #     title: Off
  #     profileMode:
  #         enabled: true
  #         title: PaperMod
  #         # imageUrl: "#"
  #         # imageTitle: my image
  #         # imageWidth: 120
  #         # imageHeight: 120
  #         subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
  #         buttons:
  #             - name: Blog
  #               url: posts
  #             - name: Tags
  #               url: tags
      menu:
          main:
              - identifier: accueil
                name: Accueil
                url: /
                weight: 3
              - identifier: realisations
                name: Réalisations
                url: /realisations/
                weight: 5
              - identifier: search
                name: Rechercher
                url: /search/
                weight: 10
              - identifier: contact
                name: Contact
                url: /contact/
                weight: 20

```

See also https://gohugo.io/content-management/multilingual/
