### DISCUSSION TITLE
Is it possible to use "created" instead of "date" frontmatter with papermod?

### DISCUSSION THREAD

**Discussion by fredrikaverpil** [adityatelange/hugo-PaperMod#1089] [Q&A]
Hi,

I would like my frontmatter for posts to look something like this:

```yml
---
title: 'Debugging Poetry with Visual Studio Code'
tags: [python]

cover:
  image: "/static/poetry_debug/debug.png"
  alt: "Visual Studio Code"
  relative: false

# PaperMod
ShowToc: true
TocOpen: true

created: 2021-04-17T02:00:00+02:00
updated: 2022-11-16T08:15:40+01:00
---
```

But with this, the papermod [archives](https://github.com/adityatelange/hugo-PaperMod/wiki/Features#archives-layout) does not work. I have to define `date` in the frontmatter to get archives to work.

Is there any way I can tell hugo/papermod to instead accept the `created` key instead?
I already have this in my hugo `config.yml`, which makes posts pick up the date from the `created` key, but it does not help in getting archives to show:

```yml
frontmatter:
  date:
    - date
    - created
```

Is this considered a bug, since I specified `frontmatter` in `config.yml` - and/or does anyone know of a workaround?
