### DISCUSSION TITLE
Archive of non-posts?

### DISCUSSION THREAD

**Discussion by fredrikaverpil** [adityatelange/hugo-PaperMod#1091] [Q&A]
I've got a `contents/posts` folder but I also have `contents/cheat-sheets`. I'd like to create an archives page for the cheat-sheets. Is this not possible?

I'm creating this, but all entries shown are posts, not cheat-sheets:

```yaml
---
title: Cheat-sheets archive
url: /archive/
layout: archives
type: "cheat-sheets"
---
```
