### DISCUSSION TITLE
Why are the colour variables of the dark theme duplicated?

### DISCUSSION THREAD

**Discussion by jesusfj710** [adityatelange/hugo-PaperMod#1219] [Q&A] [answered]
So, I was doing some research of how to change the colours of the theme and I found that we those are define in these files:

* `/assets/css/core/theme-vars.css`
  ```scss
  .dark {
    --theme: rgb(29, 30, 32);
    --entry: rgb(46, 46, 51);
    --primary: rgb(218, 218, 219);
    --secondary: rgb(155, 156, 157);
    --tertiary: rgb(65, 66, 68);
    --content: rgb(196, 196, 197);
    --hljs-bg: rgb(46, 46, 51);
    --code-bg: rgb(55, 56, 62);
    --border: rgb(51, 51, 51);
  }
  ```
* `/layouts/partials/head.html`
  ```html
    @media (prefers-color-scheme: dark) {
        :root {
            --theme: rgb(29, 30, 32);
            --entry: rgb(46, 46, 51);
            --primary: rgb(218, 218, 219);
            --secondary: rgb(155, 156, 157);
            --tertiary: rgb(65, 66, 68);
            --content: rgb(196, 196, 197);
            --hljs-bg: rgb(46, 46, 51);
            --code-bg: rgb(55, 56, 62);
            --border: rgb(51, 51, 51);
        }
   ....
    }
  ```

I have play a little with the first values and those are taked into account, but no the second ones.

Any idea @adityatelange?
