### DISCUSSION TITLE
How to get the external link type arrow?

### DISCUSSION THREAD

**Discussion by sarthakkathpalia** [adityatelange/hugo-PaperMod#1228] [Q&A]
I am unable to figure out how to get the external link arrow in the navbar. I am talking of like the one besides Discord as below

<img width="87" alt="image" src="https://github.com/adityatelange/hugo-PaperMod/assets/85081359/70a36052-d49d-420b-b5f2-3b99a8a195c7">

Can someone pls help me in this.

**Comment by c2tz** [comment]
Hello, I don't know if this has been resolved but normally when an external link is inserted in the navbar the arrow is displayed automatically.
Can you share your config file to see if there's a parameter that's blocking it. 
Because personally I'm testing on the latest version of PaperMod but I'm not having any problems.

here is my code in my config.yaml file :

```
menu:
  main:
    - identifier: android
      name: Android
      url: "https://google.fr"
      weight: 1
    - identifier: windows
      name: Windows
      url: /windows/
      weight: 2
    - identifier: services
      name: Services
      url: /services/
      weight: 3
    - identifier: about
      name: À propos
      url: /about/
      weight: 4
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 5
    - identifier: search
      name: Search
      url: /search/
      weight: 6
```
and I get this :
![chrome_NyJNrnEF7a](https://github.com/adityatelange/hugo-PaperMod/assets/95414249/776b755d-135f-499b-9765-acad6fb40d15)

**Reply by sarthakkathpalia** [reply]
Ahh, don't know why I am not getting 😕 . Here's my config file 

```
baseURL: ""
languageCode: en-us
title: Sarthak Kathpalia
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: ""
      weight: 20
    - identifier: projects
      name: Projects
      url: ""
      weight: 30
    # - identifier: experience
    #   name: Experience
    #   url: /experience
    #   weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: 
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Sarthak Kathpalia"
    subtitle: " "
    imageUrl: "home/me.png"
    imageWidth: 230
    imageHeight: 210
    buttons:
      - name: Resume
        url: "/"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:"
    - name: "linkedin"
      url: ""
    - name: "github"
      url: ""
    - name: "twitter"
      url: ""  
    # - name: "youtube"
      # url: ""
    # - name: "cv"
      # url: ""

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true

```

**Comment by c2tz** [comment]
hi, I tested with your code and I have literally no problems.
Here's the proof :

![firefox_ot2B1yIFuA](https://github.com/adityatelange/hugo-PaperMod/assets/95414249/bd0bd623-1acc-4dc3-9291-75357d3dcd2b)

What I advise you to do is :

- try the code below :
```
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: ""
      weight: 20
    - identifier: projects
      name: Projects
      url: ""
      weight: 30
    # - identifier: experience
    #   name: Experience
    #   url: /experience
    #   weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: 
    #   weight: 70
    - identifier: discord
      name: Discord
      url: "https://discord.com"
      weight: 80
```
- if not ok try again with a clean installation of PaperMod
- if not ok, check in the developer console (F12) that you don't have an error concerning an absent svg file (the arrow).
- and in the worst case simply add an arrow like this: ↗ in your config file like this :
```
- identifier: discord
     name: Discord ↗
     url: "https://discord.com"
     weight: 80
```
