### DISCUSSION TITLE
Multilingual Menus translation

### DISCUSSION THREAD

**Discussion by Arlaz** [adityatelange/hugo-PaperMod#1257] [Q&A]
Hello,

Thank you for this beautiful Theme !

I am developing a multisite and multilingual with Hugo and PaperMod. I experience some issues in translating the menu. For exemple, I want to add an _about_ page but when I switch to the French version of the site, from the home page, the menu bar still show _about_ and not _À propos_. The problem is similar with the href which is still _/about/_ and not _/a-propos/_, and the Title. 

I have deeply red the Hugo multilingual documentation and here’s what is my configuration and what I understand of the problem so far: 

- I would like to translate the menu using translation tables, not create language-specific menu entries, otherwise everything is ok.
- I’m using language specific content-dir
- I’ve created i18n/fr.yml and i18n/en.yml translation tables with the `about` identifier
- I have a global menu.yml with the content :
  ```
  - identifier: "about"
      name: about
      pageref: about
      weight: 1
  ```
- In my about.md front matter in French, I have :
  ```
  title: "À propos"
  slug: a-propos
  ```
- It seems that the navigation.MenuEntry structure only keeps the content of what's defined in the menu config, not the page frontmatter.
- However, I changed https://github.com/adityatelange/hugo-PaperMod/blob/4a924cef54081b61530a30bd69d442ae95f16561/layouts/partials/header.html#L133 to the exemple in Hugo doc menu translation : `{{- or (T .Identifier) .Name | safeHTML -}}` and now the menu is rendering correctly in French, but of course not the href and title.

I don't know if my issue is more related to Hugo or PaperMod, but I don't always have the same problem with other themes. Maybe they are just not building the menu with the same structure.

I'm not the only one with this problem :
https://github.com/adityatelange/hugo-PaperMod/discussions/967#discussion-4194382

Thank you for your help.
If I can help or do other tests let me know.

Edit:
To make it work as intended I had to change :

https://github.com/adityatelange/hugo-PaperMod/blob/4a924cef54081b61530a30bd69d442ae95f16561/layouts/partials/header.html#L129C20-L129C49

to `href="{{ ($.Site.GetPage .Identifier).Permalink | absLangURL }}`

**Comment by RoneoOrg** [comment]
I'm successfully using Papermod for [a multilingual website](https://roneo.org), both available in French and in English, and the menus are correctly translated.

Here is the full content of the file `config/_default/languages.yml`:

```
  en:
      languageName: "English"
      weight: 2
      taxonomies:
        tag: tags
        series: series
      menu:
        main:
          - identifier: search
            name: Search
            url: search/
            weight: 10
          - identifier: contact
            name: Contact
            url: /contact/
            weight: 20
          - identifier: tags
            name: Tags
            url: /tags/
            weight: 30


  fr:
      languageName: "Français"
      languageAltTitle: French
      taxonomies:
        tag: tags
        series: series
      weight: 1
      homeInfoParams:
        Title: "Roneo.org"
        Content: >
            ### Notes à propos de **Linux, Git, Hugo** et la **Jamstack**
      menu:
          main:
              - identifier: accueil
                name: Accueil
                url: /
                weight: 3
              - identifier: realisations
                name: Réalisations
                url: /realisations/
                weight: 5
              - identifier: search
                name: Rechercher
                url: /search/
                weight: 10
              - identifier: contact
                name: Contact
                url: /contact/
                weight: 20
```

and here is the full content of `config/_default/config.yml`

```
baseURL: "https://roneo.org/"
title: "Roneo.org"
paginate: 5
theme:
  - hugo-shortcode-roneo-collection
  - hugo-shortcode-roneo-button-icon-badge
  - hugo-notice
  - PaperMod
  - hugo-debug-tables

enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: true

enableEmoji: true

enableGitInfo: true

permalinks:
    article: "/:title/"

frontmatter:
  date:
  - date
  - lastmod
  - :git
  - publishDate

outputs:
    home:
        - HTML
        - RSS
        - JSON

minify:
  disableXML: true
  minifyOutput: false

params:
  displayFullLangName: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Roneo.org
  description: "Développeur Jamstack - Hugo - Netlify - Gitlab - Linux"
  keywords: [Hugo, Jamstack, Gitlab]
  # author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: ":date_long" # See https://gohugo.io/functions/dateformat/
  defaultTheme: light # dark, light
  disableThemeToggle: false
  disablePlyr: false

  # ShowPageNums: true
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowRelatedContent: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: true
  hideFooter: true
  showtoc: false
  tocopen: false
  images: ["/img/logo.png"]

  homeInfoParams:
      Title: "Roneo.org"
      Content: >
          ### Thinking out loud about **Linux**, **Git**, **Hugo** and the **Jamstack**.

DefaultContentLanguage: "fr"
defaultContentLanguageInSubdir: false
```
