### DISCUSSION TITLE
turning on search for single language website - how to / issue

### DISCUSSION THREAD

**Discussion by fimuko** [adityatelange/hugo-PaperMod#1258] [Q&A] [answered]
Hello folks, 

I am having trouble configuring the search on [my site](https://github.com/fimuko/fimuko.github.io).  
The recipe described in here: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#search-not-working-

In the `config.yml` i am skipping the whole multiple languages and I have (I am just giving part of it):

```yaml
languageCode: en-us
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: about
      name: About
      url: /
      weight: 1
    - identifier: posts
      name: Blog
      url: /Posts/
      weight: 2
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 40
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 25
```

I have `content/search.md` with:
```yaml
---
title: "Search" # in any language you want
layout: "search" # is necessary
# url: "/archive"
# description: "Description for Search"
summary: "search"
placeholder: "..."
---
```

and I am overriding https://github.com/adityatelange/hugo-PaperMod/blob/4a924cef54081b61530a30bd69d442ae95f16561/assets/js/fastsearch.js#L51
in `assets\js\fastsearch.js` with the following line:

```js
    xhr.open('GET', "index.json");
```
This is my file structure:
```bash
4	./.github/workflows/hugo.yaml
41	./.gitignore
1	./.gitmodules
0	./.hugo_build.lock
1	./archetypes/default.md
4	./archetypes/posts.md
8	./assets/js/fastsearch.js
8	./config.yml
1	./content/archives.md
4	./content/posts/2023-07-01-some-post.md
1	./content/search.md
4	./README.md
0	./resources/_gen/assets
0	./resources/_gen/images
0	./resources/_gen
32	./static/home/my_pic.jpg
52	./static/home/Search _ fimuko's blog_files/analytics.js.download
32	./static/home/Search _ fimuko's blog_files/livereload.js.download
20	./static/home/Search _ fimuko's blog_files/search.fb4e87b063089a7d6141b0d38c367971c8137bc37b8731be5a422ff95f9bc61f.js.download
108	./static/home/Search _ fimuko's blog_files
720	./themes/PaperMod
```
Not sure what else I should consider... I would be greatful for any suggestion.

**Comment by RoneoOrg** [comment]
In `config.yml` I have the following lines, in the `params` section:

```
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
```

Maybe this can unlock something for you
