### DISCUSSION TITLE
Unable to Apply Font-Size Property to Inline Code

### DISCUSSION THREAD

**Discussion by Tx0actical** [adityatelange/hugo-PaperMod#1260] [Q&A] [answered]
I modified the default PaperMod font to FiraCode. But it turns out, inline code blocks don't adjust to `font-size` property I set in the `assets/css/extended/custom_styles.css` file:

```css
@font-face {
    font-family: 'FiraCode';
    src: url('/fonts/FiraCode-Regular.ttf') format('truetype'),
        url('/fonts/FiraCode-Bold.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
body {
    font-family: 'FiraCode', sans-serif;
    font-size: 14px;
}
pre, code {
    font-family: 'FiraCode', monospace;
    font-size: 18px;
}
```
`font-family` applies to everything including the inline code elements whereas `font-size` is applies to everything except the inline code. Here's a screenshot from one of the posts:

![anomaly](https://github.com/adityatelange/hugo-PaperMod/assets/88306361/e59e139d-cace-4320-98e6-4a51932aa0fe)

Note that the inline code looks smaller than the rest, also I had to increment monospace more as compared to sans-serif to compensate for less text-size increase per pixel change, otherwise at equal values FiraCode in the `<code>` looks smaller than FiraCode in `<body>` (This is also a mystery).
