### DISCUSSION TITLE
Example of a post cover image?

### DISCUSSION THREAD

**Discussion by jamesbraza** [adityatelange/hugo-PaperMod#1269] [Q&A] [answered]
I am trying to figure out what a post cover image is.  The current [Wiki on Post Cover Image](https://github.com/adityatelange/hugo-PaperMod/wiki/Features#post-cover-image) doesn't detail what a post cover image actually is, it just shares how to use them.

Will a post cover image add images on the right half of the home page's tiles?

<img width="776" alt="image" src="https://github.com/adityatelange/hugo-PaperMod/assets/8990777/a033fb07-1e0b-43e5-80f9-83018088a0bc">

---

I tried actually downloading the template and adding a URL, but it's not working:

```yaml
cover:
    image: "https://en.wikipedia.org/wiki/File:Pale_Blue_Dot.png"
    caption: "test" # display caption under cover
    relative: true # when using page bundles set this to true
```

![image](https://github.com/adityatelange/hugo-PaperMod/assets/8990777/312bf1f0-ab25-438d-b6b3-bf00e1dca41f)

Is is possible to have a post cover image only on the right side of a tile?

**Comment by diomed** [comment, marked as answer]
`https://upload.wikimedia.org/wikipedia/commons/7/73/Pale_Blue_Dot.png`

you have to link picture file itself, not link where image is.

**Comment by jamesbraza** [comment]
When using the correct link, here's how the `cover` looks:

```yaml
cover:
    image: "https://upload.wikimedia.org/wikipedia/commons/7/73/Pale_Blue_Dot.png"
    caption: "test" # display caption under cover
    relative: true # when using page bundles set this to true
```

![screenshot of cover image](https://github.com/adityatelange/hugo-PaperMod/assets/8990777/e299e583-b56a-4fcd-a554-2a8c29b20f68)
