### DISCUSSION TITLE
Social icons not showing, div is empty

### DISCUSSION THREAD

**Discussion by Zeitverschreib** [adityatelange/hugo-PaperMod#1280] [Q&A]
I just installed the latest Hugo on Linux and added PaperMod 7.0.

Everything seems to be working fine so far, except for one issue: I can't get any social icons to show.

From config.yml:

```
params:
    homeInfoParams:
        Title: Testsite
        Content: Can be Info, links, about...

socialIcons:
  - name: "kofi"
    title: "<custom title>"
    url: "https://kofi.com"
```

From the page's source code:

```
<main class="main"> 
<article class="first-entry home-info">
    <header class="entry-header">
        <h1>Testsite</h1>
    </header>
    <div class="entry-content">
        Can be Info, links, about&hellip;
    </div>
    <footer class="entry-footer">
        <div class="social-icons">
</div>

    </footer>
</article>
```
It seems as if the social-icons div is not filled at all. What am I missing?
