### DISCUSSION TITLE
How to get the search working?

### DISCUSSION THREAD

**Discussion by shellheim** [adityatelange/hugo-PaperMod#1306] [Q&A] [answered]
I looked at the [wiki](https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page) to find out and all it says that I need to enable these options in my config.yaml : 

```yaml
  # Search
  outputs:
    home:
      - HTML
      - RSS
      - JSON
```
and I added an option to reach the search page by listing it on the navbar : 

```yaml
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40
```
But looking through assets/js/fastsearch.js I found I need a index.json file through which fuse.js can search. How do I generate that?
