### DISCUSSION TITLE
how to translate homeInfoParams title and content.

### DISCUSSION THREAD

**Discussion by kirmola** [adityatelange/hugo-PaperMod#1330] [General]
I am trying to translate homeInfoParams title and content, how would I do that?

**Comment by RoneoOrg** [comment]
These lines in `config.yml` should work:

```
languages:
    fr:
        weight: 1
        title: "PaperMod en français"
        homeInfoParams:
            Title: "Bonjour tout le monde"
            Content: "Bienvenu sur le site en français"
    en:
        weight: 2
        title: "PaperMod in english"
        homeInfoParams:
            Title: "Hi there!"
            Content: "Welcome to english website"
```
