### DISCUSSION TITLE
Why do the colors change in order when switching themes?

### DISCUSSION THREAD

**Discussion by rea1shane** [adityatelange/hugo-PaperMod#1343] [General]
I want to add delay when theme transition, I add these CSS:

```css
* {
    transition: color 200ms ease-in-out, background 200ms ease-in-out;
}
```

But I noticed that the color transitions of the elements are not simultaneous, but sequential, why?

![record](https://github.com/adityatelange/hugo-PaperMod/assets/93363751/b3bcb81a-0dad-4d77-8b92-07ace5d605e6)

To Reproduce:

1. New hugo site add set paper-mod theme.
2. Add above CSS.
3. Add a post.
4. Start server, enter the post and switch theme.

And I found https://github.com/adityatelange/hugo-PaperMod/pull/407, is it the best way to do this thing? It modifies a lot of files and I want to as few as possible.
