### DISCUSSION TITLE
How to use prefers-color-scheme CSS selection with the dark / light switch?

### DISCUSSION THREAD

**Discussion by bee-san** [adityatelange/hugo-PaperMod#135] [General]
Hey!

I'm re-designing the CSS for tables.

I have this CSS:

```css
@media (prefers-color-scheme: light) {
    tbody tr:nth-of-type(even) {
    background-color: #f3f3f3;
    }
}

@media (prefers-color-scheme: dark) {
    tbody tr:nth-of-type(even) {
    background-color: #383838;
    }
}
```

This operates based on what the browser / OS settings are.

But the user can prefer dark mode, but select light mode in the theme and this then breaks.

How would I go around detecting when the switch is flicked so it can change the CSS? :)

**Comment by adityatelange** [comment]
@bee-san We use a event listener to switch the theme.
You may find it below
https://github.com/adityatelange/hugo-PaperMod/blob/77ff1e6b452ad64eeee5178667827323d0a1644d/layouts/partials/footer.html#L54-L67

**Comment by kdkasad** [comment]
@bee-san If you want to stick to CSS, you can check whether the `body` element has the `dark` class:
```css
tbody tr:nth-of-type(even) {
    background-color: #f3f3f3;
}

body.dark tbody tr:nth-of-type(even) {
    background-color: #383838;
}
```

**Reply by bee-san** [reply]
This does it!!! Damnn thanks!!!!

**Reply by sourcevault** [reply]
Hi,

I have a CSS issue similar to Ben.

What is the general technique for writing CSS shortcode to take into account dark mode ?

would something like what is shown below do the trick :

```css
    .box-shortcode.important {
      background: #f7ec2c7d;
    }

    .box-shortcode.important.dark {
      background: #757575;
    }
```
