### DISCUSSION TITLE
featured image doesn't appear in social media preview

### DISCUSSION THREAD

**Discussion by DolevRavid** [adityatelange/hugo-PaperMod#1513] [Q&A]
Hi everyone,

I'm loving this fantastic theme! It's definitely one of the best I've come across.
There's just one minor issue preventing it from being perfect. When I share a link on Facebook or LinkedIn, the featured image doesn't appear in the preview.
Does anyone know how to fix this?

Thanks,
Dolev
http://dolev.blog

**Comment by LevYas** [comment]
Use this:
```
cover:
    image: "cover.png"
    alt: "your alt"
    relative: true # Must be explicitly set in the front matter to work correctly
```

And build Hugo in production mode (not via `hugo server`). Although looks like you've already solved that :)
