### DISCUSSION TITLE
How to set Metadata for Twitter Card for `index.html` in Profile Mode

### DISCUSSION THREAD

**Discussion by Tauheed-Elahee** [adityatelange/hugo-PaperMod#1546] [Q&A] [answered]
Hello,

I'd like to know how to set the metadata needed for a twitter card of the base `index.html` page of the website. When using HomeInfo mode, I can use the `title`,`desciption` and `cover` page param to set the meta data for twitter cards. However when ProfileMode is `enabled` then it does not show. It only shows the profile image.

The hugo config file `hugo.yml` is:

```yaml
baseURL: https://example.ca
languageCode: en-ca
title: 'Example.ca'
theme: ["PaperMod"]

params:
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  profileMode:
    enabled: ture
    title: "Example.ca"
    subtitle: "Description of page."
    imageUrl: "/home/icon.jpg"
    imageTitle: "Example.ca icon image"
  socialIcons:
    - name: "youtube"
      url: "https://www.youtube.com/"
  cover:
    linkFullImages: true
  assets:
    disableHLJS: true
    favicon: "/assets/favicon.ico"
    favicon16x16: "/assets/favicon-16x16.ico"
    favicon24x24: "/assets/favicon-24x24.ico"
    favicon32x32: "/assets/favicon-32x32.ico"
    favicon48x48: "/assets/favicon-48x48.ico"
    favicon64x64: "/assets/favicon-64x64.ico"
    favicon96x96: "/assets/favicon-96x96.ico"
    favicon128x128: "/assets/favicon-128x128.ico"
    favicon192x192: "/assets/favicon-192x192.ico"
    favicon256x256: "/assets/favicon-256x256.ico"

menu:
  main:
    - identifier: "Home"
      name: "Home"
      url: "/"
      weight: 10
    - identifier: "Videos"
      name: "Videos"
      url: "/videos"
      weight: 20
    - identifier: "Credits"
      name: "Credits"
      url: "/credits"
      weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
```

And `content/_index.md` is:

```markdown
---
title: 'Example.ca'
description: "Description of page."
date: 2024-06-26T11:30:19-04:00
cover:
  image: "/home/icon.jpg"
  alt: "Icon for Example.ca"
  caption: "Example.ca"
  relative: false
draft: false
---

# Header 1

Hello World!
```

The body of `content/_index.md` does not show in the front page of the website so I am assuming it does not use the metadata from `content/_index.md`. I'm trying to figure out where it is coming from.

Though when deployed, the title, description, and image show in the appropriate `<meta>` tags in the `head`.
