### DISCUSSION TITLE
Disable list of posts in the Home-info mode

### DISCUSSION THREAD

**Discussion by btzo** [adityatelange/hugo-PaperMod#1548] [Q&A]
Is there a simple way of not showing the list of posts on the home page ?

See the image below for reference

![homeinfo](https://github.com/adityatelange/hugo-PaperMod/assets/1796534/0a600861-2721-4919-aea6-82ec3340b785)

**Comment by btzo** [comment]
The solution that I found was to set `hiddenInHomeList: true` parameter at the start of each file that I posted. 

I was expecting a variable in the config, something like `hidePostsInHomePage`, 
but as far as I understand, this doesn't exist. That's right?

**Reply by kirmola** [reply]
how are your posts visible? Mine aren't. can you guide me what am I doing wrong here. I have used just this: 
 ```
params:
 homeInfoParams:
    hiddenInHomeList: false
    Title: "Welcome"
    Content: >
      sample content.
languages:
  en:
    languageName: "English"
    contentDir: content/en
    languageCode: en-US
    # defaultContentLanguageInSubdir: true
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series


```
here is a scrnshot of directory structure:
![image](https://github.com/adityatelange/hugo-PaperMod/assets/90174212/1fb10d0a-91e7-427b-bbc1-aa0c549cec00)
