### DISCUSSION TITLE
How to disable smooth scrolling?

### DISCUSSION THREAD

**Discussion by nullvm** [adityatelange/hugo-PaperMod#1550] [Q&A] [answered]
I have tried to add

```css
html {
  scroll-behavior: auto !important;
}
```

in the following css files: `post-single.css`, `main.css`, `reset.css`, and `blank.css` but it still has the smooth scrolling behavior.
