### DISCUSSION TITLE
How to set fonts?

### DISCUSSION THREAD

**Discussion by TheKamboy** [adityatelange/hugo-PaperMod#1561] [Q&A]
I have no clue on how to set fonts.
I'm using the [VDS Font](https://www.fontspace.com/vds-font-f23533). I packaged it using font squirrel to make it woff2 and woff.
I've looked at other discussions and none of the discussions helped with setting the font for the website.

"assets/css/extended/vdsfont.css"
``` css
/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on July 29, 2024 */

@font-face {
  font-family: "vdsregular";
  src:
    url("fonts/vds-r5l3-webfont.woff2") format("woff2"),
    url("fonts/vds-r5l3-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "vdsitalic";
  src:
    url("fonts/vdsitalic-m5wr-webfont.woff2") format("woff2"),
    url("fonts/vdsitalic-m5wr-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "vdsbold_italic";
  src:
    url("fonts/vdsbolditalic-8aqz-webfont.woff2") format("woff2"),
    url("fonts/vdsbolditalic-8aqz-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "vdsbold";
  src:
    url("fonts/vdsbold-ban5-webfont.woff2") format("woff2"),
    url("fonts/vdsbold-ban5-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}
```
