### DISCUSSION TITLE
Writing markup front-matter cover image

### DISCUSSION THREAD

**Discussion by pacientes** [adityatelange/hugo-PaperMod#159] [Q&A] [answered]
Hello.

I found 'cover front-matter' feature.
But I don't know what is really mean, and how to use that.

I need what's that and some example to used please.
Thank you.

**Comment by adityatelange** [comment, marked as answer]
Read https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#post-cover-image

**Reply by pacientes** [reply]
I am confused about how to write `image:`.

In my case...
Some image files in `posts` directory and use `![image](cover.png)` like this
post markdown path : posts\2020\12\review_deep_learning_from_scratch_3.md
cover image path : posts\2020\12\review_deep_learning_from_scratch_3\cover.png

```yml
cover:
    image: "<image path/url>"
    # can also paste direct link from external site
    # ex. https://i.ibb.co/K0HVPBd/paper-mod-profilemode.png
    alt: "<alt text>"
    caption: "<text>"
```

How should I write that code?
