### DISCUSSION TITLE
How do I change the HomeInfo title and content to be different for other languages?

### DISCUSSION THREAD

**Discussion by Thinner8251** [adityatelange/hugo-PaperMod#1630] [Q&A]
It seems like it's showing the same title and content for all languages.

**Comment by adityatelange** [comment]
https://github.com/adityatelange/hugo-PaperMod/blob/2378012732ae821b7f987a941919cbb06b25a0d5/config.yml#L99-L103

**Reply by PavoDive** [reply]
@adityatelange Thanks for a wonderful theme! Could you please describe in detail what should be done to have different titles and contents for different languages? I read the part of the code you just linked, but honestly could not figure what should be done.

Another question ([1330](https://github.com/adityatelange/hugo-PaperMod/discussions/1330) ) suggested to have:

```
languages:
    fr:
        weight: 1
        title: "PaperMod en français"
        homeInfoParams:
            Title: "Bonjour tout le monde"
            Content: "Bienvenu sur le site en français"
    en:
        weight: 2
        title: "PaperMod in english"
        homeInfoParams:
            Title: "Hi there!"
            Content: "Welcome to english website"
```

But if I do that I get `WARN  Skip unknown config key "homeinfoparams"`.
