### DISCUSSION TITLE
How do I get social icons to display?

### DISCUSSION THREAD

**Discussion by clarelgibson** [adityatelange/hugo-PaperMod#1674] [Q&A] [answered]
I have added the following to `Hugo.yaml`:

```
socialIcons:
  - name: "github"
    url: "https://github.com/clarelgibson"
  - name: "linkedin"
    url: "https://linkedin.com/in/clarelgibson"
```

However, nothing happened. There are no social icons displaying on my site. What am I doing wrong?

**Comment by jasonbraganza** [comment]
hello @clarelgibson, would you try the names (github/linkedin) without the quotes? suggesting this, because this is how I have it in my config file. like below

``` yaml
    - name: github
      url: "https://github.com/jasonbraganza"
```

**Reply by clarelgibson** [reply, marked as answer]
Thank you for the suggestion. I managed to solve my issue with the following steps:

1. I moved the `socialIcons` code to sit within the `params` section of my `hugo.yaml` file. The instructions on the [wiki](https://github.com/adityatelange/hugo-PaperMod/wiki/Variables#socialicons) were not clear that this needs to sit within `params` but looking at the source files for another site built with the PaperMod theme I saw that this was the case.
2. I enabled the `profileMode` variables within `params` so that my home page is now in profile mode, with the below code:

```
  profileMode:
    enabled: true
    title: "Clare Gibson"
    subtitle: "Data analyst, product owner, lifelong learner"
    imageUrl: "img/clare-01.png"
    imageWidth: 150
    imageHeight: 150
```

With the 2 updates above I now have the social icons displayed on my home page. It appears the social icons only work if you are using the Profile Mode, although this wasn't stated in the documentation as far as I could see.
