### DISCUSSION TITLE
How to set menu links to open in a new tab? I've added the target attribute but it didn't work. I hope someone can kindly tell me the solution.

### DISCUSSION THREAD

**Discussion by rickeygong** [adityatelange/hugo-PaperMod#1680] [Q&A] [answered]
I'm using the PaperMod version 8.0.

How to set menu links to open in a new tab? I've added the target attribute but it didn't work. I hope someone can kindly tell me the solution.

```  yaml
menu:
      main:
        - identifier: travelling
          name: Travelling
          url: https://www.travellings.cn/go.html
          target: _blank  # This specifies that a new TAB opens
          weight: 1
```
