### DISCUSSION TITLE
Custom Fonts?

### DISCUSSION THREAD

**Discussion by boehs** [adityatelange/hugo-PaperMod#220] [Q&A]
Title, I specifically want to change the header font. what would I apply the style to in the custom css?

Cheers

**Comment by kdkasad** [comment]
If you mean the page header (i.e. site title and menu), then:
```css
header.header {
    font-family: "<other font>";
}
```

If you mean the post title, then:
```css
header.post-header {
    font-family: "<other font>";
}
```

**Reply by boehs** [reply]
thank you - but it appers fonts via @font-face do not work?

I do 

```css
@font-face {
    font-family: 'dillanregular';
    src: url('fontdir') format('woff2'),
        url('fontdir') format('woff');
    font-weight: normal;
    font-style: normal;

}
``` 
in blank.css and reference the font later. I have confirmed the directory is reachable
