### DISCUSSION TITLE
Create a multiline title in profile mode

### DISCUSSION THREAD

**Discussion by sid-r-singh** [adityatelange/hugo-PaperMod#228] [Q&A] [answered]
Is there any way to split the title into multiple lines in profile mode ?

**Comment by adityatelange** [comment, marked as answer]
```
params:
    profileMode:
        enabled: true
        title: "PaperMod


        is best !"
        subtitle: Hi I am a coder
```

![image](https://user-images.githubusercontent.com/21258296/107559118-a9889600-6c01-11eb-88f0-323f3834d088.png)

p.s. The text is only for illustration purpose, please don't take it seriously
