### DISCUSSION TITLE
how can I enlarge the picture in the article

### DISCUSSION THREAD

**Discussion by gsh3ll** [adityatelange/hugo-PaperMod#305] [Q&A]
Hello, how can I enlarge the picture in the article? I don't have web-design knowledge, I tried to add `LightGallery`, and I repeatedly reported errors, hoping to integrate `LightGallery`.

**Comment by kdkasad** [comment]
Are you asking how to enlarge an image in a post or are you asking how to set up LightGallery?

To enlarge an image, you can use the `width` and/or `height` parameter of the `figure` shortcode. See [this page](https://gohugo.io/content-management/shortcodes/#figure) of the Hugo docs for more info.

**Comment by gsh3ll** [comment]
Tried to read the front-end information, but still can’t successfully set up LightGallery.please teach me how to set up LightGallery?😂

**Comment by gsh3ll** [comment]
I followed your tutorial, created a new search page and set config.yml, but my search page seems to be invalid.
search.md:
```markdown
---
title: "Search" # in any language you want
layout: "search" # is necessary
# url: "/archive"
# description: "Description for Search"
summary: "search"
---
```
config.yml:
```yml
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    outputs:
        home:
            - HTML
            - RSS
            - JSON # is necessary
```
My posts:
```markdown
searchHidden: false
```
![image](https://user-images.githubusercontent.com/64195264/109933793-c39c2c80-7d06-11eb-8f9b-556ea72333e2.png)
![image](https://user-images.githubusercontent.com/64195264/109933871-d6aefc80-7d06-11eb-995d-ceee7067c181.png)
