### DISCUSSION TITLE
Change width of the content

### DISCUSSION THREAD

**Discussion by r3pek** [adityatelange/hugo-PaperMod#442] [General]
Is there a (css) way to change the width of the content?

**Comment by pixelfabs** [comment]
Yes. The thing you're looking for is in `theme-vars.css` and is called `--main-width` under `:root`

**Reply by fulljackz** [reply]
Thanks for your reply. I'm also looking to change the main-width without editing the default template.
I tried to add `theme-vars.css` in `static/assets/css` without success. Any hint about this ?

Regards,

**Reply by ichard26** [reply]
@fulljackz 

![image](https://user-images.githubusercontent.com/63936253/152721738-2810595f-c909-4347-a8c8-253c11128241.png)

```css
main {
  --main-width: [REPLACE WITH VALUE];
}
```

Putting this in `/assets/css/extended/overrides.css` should work, [IRL example](https://github.com/ichard26/ichard26.github.io/blob/652009a0c7f865e74e6ecfe92d7269248e3fff34/assets/css/extended/overrides.css#L1-L3) on my Hugo website :)

**Reply by fulljackz** [reply]
Nice, it works !
I was trying to change the wrong file. I forgot that 5 minutes of reading documentation could prevent 5 hours of debugging :grimacing: 

Thanks.

**Reply by abey79** [reply]
I'm trying to do the same but somehow it seems that my `/assets/css/extended/overrides.css` file is ignored. Is there something to be done way to "enable" it?

Edit: nvm, I got it working

**Reply by meashiri** [reply]
@abey79  please add what you did to get it working

**Reply by abey79** [reply]
@meashiri Honestly, I don't remember. [Here](https://github.com/abey79/abey79.github.io) is my site if you want to check it out.

**Reply by meashiri** [reply]
I wanted to add what worked for me. 

This is my _assets/css/extended/overrides.css_  that worked. 

```css
:root {
    --line-height:1.1em;
    --post-width:960px;
    --monospace: monospace;
}
.main.post {
    --main-width:880px;
    position: relative;
	min-height: calc(100vh - var(--header-height) - var(--footer-height));
	max-width: calc(var(--main-width) + var(--gap) * 2);
	margin: auto;
    margin-right: 50px;
	padding: var(--content-gap)var(--gap)0;
}

.post-content {
	font-size: 14px;
    line-height: 1.2em;
	color: var(--content);
}
```

**Reply by douyixuan** [reply]
Thx, It worked.

**Comment by tkgregory** [comment]
I got this working by adding an *assets/css/extended/theme-vars.css* file with one entry:

```css
:root {
    --main-width: 1200px;
}
```
