### DISCUSSION TITLE
[Feature Request] Small thumbnail to the left/right of the title

### DISCUSSION THREAD

**Discussion by Hattomo** [adityatelange/hugo-PaperMod#475] [Ideas]
First, Thank you for your beautiful theme.

I have one question.

I tried to set post cover image, but it's too big.

![Screenshot 2021-07-21 154341](https://user-images.githubusercontent.com/45988993/126448576-9f6021aa-337c-4437-bbaf-85e29b302afc.png)

I think it would be nice to have option which show small thumbnail to the left/right of the title.

For example, Google search ( this show small thumbnail to the right of the title.)
![Screenshot 2021-07-21 162201](https://user-images.githubusercontent.com/45988993/126448873-c22d8498-3558-4f31-8d3b-141a16c3bb12.png)

How to implement this? and Do you have any plan for implement this?

Thanks in advance.

**Comment by sarkrui** [comment]
It would be great to have such a feature, as I wouldn't like to have all cover images taking up the space. But I only know a little bit about front-end development. So I hide them all, and only reveal them when the mouse hovers. 
![bOalXDG](https://user-images.githubusercontent.com/14228455/127168159-13a60a59-d50b-4a96-b3d6-d77c249a0850.gif)

### How to 
inject the below snippets into the `themes/PaperMod/assets/css/common/post-entry.css`
```css
.post-entry > .entry-cover{
    display: none;
    opacity: 0;
}

.post-entry:hover .entry-cover{
    display: block;
    opacity: 1;
    /* "both" tells the browser to use the above opacity
    at the end of the animation (best practice) */
    -webkit-animation: display-none-transition 0.5s both;
    animation: display-none-transition 0.5s both;
}
@-webkit-keyframes display-none-transition {
    0% {
      opacity: 0;
    }
}
@keyframes display-none-transition {
    0% {
        opacity: 0;
    }
}
```
@adityatelange perhaps you would like to include such a styling option in the theme? for example, `enableCoverHoverEffect: true`
