### DISCUSSION TITLE
PR proposal for font-size breakpoints

### DISCUSSION THREAD

**Discussion by danielfdickinson** [adityatelange/hugo-PaperMod#496] [Ideas]
I've got some CSS I use for increasing the font size as the screen resolution gets larger (because often higher resolution is means higher DPI, and I'm not aware of a working way to check DPI using only CSS, especially on 2K and 4K displays).

In addition, this enhances the experience for those with low vision (but not completely blind).

The proposed CSS (I would add this in the appropriate assets/css files, if the idea gets accepted) is:

```css
@media not speech {
    body {
        font-size: 16px;
    }
}

@media screen and (min-width: 28em) {
    body {
        font-size: 17px;
    }
}

@media screen and (min-width: 36em) {
    body {
        font-size: 18px;
    }
}

@media screen and (min-width: 48em) {
    body {
        font-size: 19px;
    }
}

@media screen and (min-width: 56em) {
    body {
        font-size: 20px;
    }
}

@media screen and (min-width: 64em) {
    body {
        font-size: 21px;
    }
}
```
Because base font size would no longer be fixed, I also propse the following changes:

```css
.footer,
.post-meta {
    font-size: .8em;
}

#menu a {
    font-size: .9em;
}

.logo a {
    font-size: 1.6em;
}
```

Thoughts?
