### DISCUSSION TITLE
Which Layout Do I Use for an "About Me" page?

### DISCUSSION THREAD

**Discussion by julianchso** [adityatelange/hugo-PaperMod#517] [Q&A]
Title. So no breadcrumbs or anything in the title. Just an h1.

Stupid question but I'm totally new to using static site generators and coding in general.

**Comment by OxNinja** [comment]
I use a bad but quick method:

Create `content/about.md`:

 ```md
---
title: "About"
---

My about content,
```

In `config.yml`:

```yml
...
menu:
  main:
    - identifier: about
    name: About Me
    url: /about/
    weight: 1
...
```

**Reply by shellheim** [reply]
Since hugo uses toml now, how do I implement this in a toml file? General conversion like this : 
```toml
[menu.main]
identifier = "about"
name = "About Me"
url = "/about/"
weight = 1
```  
doesn't work.  
Here's my hugo.toml if that helps : 
```toml
baseURL = 'https://localhost:1313/'
languageCode = 'en-us'
title = 'The Shell Archives'
theme = 'PaperMod'

[params]
defaultTheme = "dark"

ShowReadingTime = true
ShowShareButtons = true
ShareButtons = ["twitter", "reddit"]
ShowCodeCopyButtons = true

[params.homeInfoParams]
Title = "Hi there 👋 "
Content = "Books"

[[params.menu.main]]
name = "Test"
url = "history/"
```  
here 'history' is a directory inside content/ which has a few posts. I want that when this item in the menu is clicked the page only shows posts from the content/history/ directory.
