### DISCUSSION TITLE
How to configure `socialIcons` with TOML config format?

### DISCUSSION THREAD

**Discussion by svenjacobs** [adityatelange/hugo-PaperMod#580] [Q&A] [answered]
Hi all 👋🏼 

How do I configure `socialIcons` when the config file is in the TOML format? I only find examples for YAML.  
I tried

```toml
[[params.socialIcons]]
name = 'github'
url = '...'

[[params.socialIcons]]
name = 'email'
url = '...'
```

and

```toml
[params]
socialIcons = [
  { name = 'github', url = '...' },
  { name = 'email', url = '...' },
]
```

but the icons don't appear 😞
