### DISCUSSION TITLE
Multilingual Profile Mode , Broken Pic

### DISCUSSION THREAD

**Discussion by gitsite93** [adityatelange/hugo-PaperMod#594] [Q&A]
Hello, I'm making the website in 2 languages and I would like 2 different profile mode for each language.
What’s the right way to do that? 

If I try to put two profile mode in the languages section they works but the image of the second profile mode is always not found even if is the same of the first one.

Tried with different browsers and clean cache.

hope to get a feedback from you, have a nice day and thanks

**Comment by adityatelange** [comment]
Hi @gitsite93 , can you please share your project repo or `config.yml`?

**Comment by gitsite93** [comment]
ASAP, I’m very busy in the next few days
Thanks

**Comment by shadyalfred** [comment]
Can someone post the config to do this? I've tried yet failed to change the name and the url of the buttons for different languages.

**Comment by shadyalfred** [comment]
I've tried this
```toml
[params.profileMode]
  enabled = true

[languages]
  [languages.ar]
    languagedirection = 'rtl'
    contentDir = 'content/ar'

    [languages.ar.params]
      [[profileMode.buttons]]
        name = 'أرشيف'
        url = '/ar/archive'

      [[profileMode.buttons]]
        name = 'مقالات'
        url = '/ar/posts'

  [languages.en]
    contentDir = 'content/en'

    [languages.en.params]
      [[profileMode.buttons]]
        name = 'Posts'
        url = '/en/posts'

      [[profileMode.buttons]]
        name = 'Archive'
        url = '/en/archive'
```

But it doesn't show any buttons in both languages. If I add `params` before it so it becomes `params.profileMode.buttons` the button is shown in both languages

**Comment by shadyalfred** [comment]
Oh ok, I've found my issue, I should have enabled the profile mode in both languages

```toml
[languages]
  [languages.ar]
    languagedirection = 'rtl'
    contentDir = 'content/ar'

    [languages.ar.params.profileMode]
      enabled = true

      [[languages.ar.params.profileMode.buttons]]
        name = 'أرشيف'
        url = '/ar/archive'
      [[languages.ar.params.profileMode.buttons]]
        name = 'مقالات'
        url = '/ar/posts'


  [languages.en]
    contentDir = 'content/en'

    [languages.en.params.profileMode]
      enabled = true

      [[languages.en.params.profileMode.buttons]]
        name = 'Posts'
        url = '/en/posts'
      [[languages.en.params.profileMode.buttons]]
        name = 'Archive'
        url = '/en/archive'
```
