### DISCUSSION TITLE
How can I show the cover image in the list in tags and categories pages?

### DISCUSSION THREAD

**Discussion by pottekkat** [adityatelange/hugo-PaperMod#631] [Q&A] [answered]
I have added these in the front matter expecting to see the cover image in the list view in all places.

```
    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page
```

But I'm only seeing the cover image in the list view in the home page and not in the tags page or the categories page.

How can I set the list view to display the cover image in every page and not just the home page?

_I am new to Hugo and it is not super obvious to me on how I can configure this. Any help would be appreciated._

@danielfdickinson do you have an idea about this?

Reference: [navendu.me](https://navendu.me)

**Comment by danielfdickinson** [comment, marked as answer]
>How can I set the list view to display the cover image in every page and not just the home page?

You need to modify the CSS. The issue is:

```css
.tag-entry .entry-cover {
    display: none;
}
```
Reference: https://github.com/adityatelange/hugo-PaperMod/blob/3bcafa0be9461124fcd2a09a58799e2fd1e7a505/assets/css/common/post-entry.css#L50

You can override that behavior [using custom CSS](https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#bundling-custom-css-with-themes-assets).

Hope that points you in the right direction.
