### DISCUSSION TITLE
How do I add a new page - say thank you page?

### DISCUSSION THREAD

**Discussion by abishek** [adityatelange/hugo-PaperMod#669] [Q&A]
I am trying to add a new page to my papermod based site. I created a content/thankyou.md but it does not link to /thankyou/. I cannot find a thankyou folder in the generated site as well. How do I add this page to my site? Thanks!

**Comment by Thorgrimson** [comment]
i guess you want the page to appear in the Top-Menu? For this you have to add in the config.yml:
```
menu:
  main:
    - identifier: thankyou
      name: Thank you #this is the text wich is displayed in the menu
      url: /thankyou/
      weight: 10 # with this number you indicate on wich position the menu entry appears
```
