### DISCUSSION TITLE
The background color of code blocks (syntax highlighting) do not change when I change the chroma style.

### DISCUSSION THREAD

**Discussion by yseeker** [adityatelange/hugo-PaperMod#721] [Q&A]
Following [this](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#using-hugos-syntax-highlighter-chroma), I am trying to change the "style" in config.yml of the syntax highlighting by changing the style (e.g. abap, colorful like [here](https://xyproto.github.io/splash/docs/all.html) from the default (monokai)), but only the color of font changes and the background color in code block does not change (the color is always black like monokai).
Do I miss something? Could anyone kindly tell me what is wrong?

I am using the following setting.
```yaml
params:
    assets:
        disableHLJS: true

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        #anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: false
        #noClasses: false
        style: abap
```

**Comment by tim-hilt** [comment]
The background-color is specified via the custom property `--hljs-bg`, which is defined in `assets/css/core/theme-vars.css` like so:

``` css
:root {
    /* ... */
    --hljs-bg: rgb(28, 29, 33);
    /* ... */
}

.dark {
    /* ... */
    --hljs-bg: rgb(46, 46, 51);
    /* ... */
}
```

You can overwrite these values by adding the following in `YOUR-SITE-ROOT/assets/css/extended/somefilename.css`:

``` css
:root {
    /* ... */
    --hljs-bg: #ff0000;
    /* ... */
}

.dark {
    /* ... */
    --hljs-bg: #00ff00;
    /* ... */
}
```

Of course adapt the shown color-values to something you find fitting.
