### DISCUSSION TITLE
More info in profileMode page

### DISCUSSION THREAD

**Discussion by alexdrm98** [adityatelange/hugo-PaperMod#860] [General]
i have enabled profileMode in my config. it only shows title and subtitle as exactly mentioned in the config.
```
params:
    profileMode:
        enabled: true
        title: "<Title>" # optional default will be site title
        subtitle: "This is subtitle"
```
How can i add more info into my profileMode page?
