### DISCUSSION TITLE
search has something wrong

### DISCUSSION THREAD

**Discussion by XXiaoA** [adityatelange/hugo-PaperMod#874] [Q&A]
I have a post 
![Screenshot_2022-04-07-21-16-53-381_com mmbox xbrowser](https://user-images.githubusercontent.com/62557596/162207702-b0412687-eac6-44f7-810f-8db139b9bb37.jpg)

but i can't search it 
![Screenshot_2022-04-07-21-16-57-487_com mmbox xbrowser](https://user-images.githubusercontent.com/62557596/162207737-386a76e1-c9b2-4efe-8202-2ae5e624f00b.jpg)

How do i solve it? Thank you in advance

**Comment by adityatelange** [comment]
Hi @XXiaoA 

If you check here, https://xxiaoa.github.io/index.json .The post is not added here?

**Reply by XXiaoA** [reply]
@adityatelange 
oh, yep. The post isn't added. So how to sovle it?

**Reply by adityatelange** [reply]
Can you find out why the post is not added? No such issues we have in demo deployed.

**Reply by XXiaoA** [reply]
Really sorry. I am new to Hugo.  I have tried to google but I can't find out that is why. Here is my `config.yml` , hope it is helpful

```yml
baseURL: "https://xxiaoa.github.io/"
title: XXiaoA's Blog
paginate: 5
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: XXiaoA's Blog
  description: "My heart is with you"
  keywords: [Blog, XXiaoA, Daily, Programming]
  author: XXiaoA
  # author: ["Me", "You"] # multiple authors
  images: ["<https://s2.loli.net/2022/02/13/LQZurKxEpmwolbD.jpg>"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  comments: true

  label:
    text: "Home"
    # icon: /apple-touch-icon.png
    icon: https://s2.loli.net/2022/02/13/LQZurKxEpmwolbD.jpg
    iconHeight: 35


  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: email
      url: "mailto:isxxiaoa@gmail.com"
    - name: telegram
      url: "https://t.me/XXiaoA"
    - name: github
      url: "https://github.com/XXiaoA"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/xxiaoa/blog/tree/main/content"
    Text: " Edit" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: Archives
      url: archives/
      weight: 5
    - name: Categories
      url: categories/
      weight: 10
    - name: Tags
      url: tags/
      weight: 15
    - name: Search
      url: search/
      weight: 20
    - name: About
      url: about/
      weight: 25
```
