### DISCUSSION TITLE
Menu disappear suddenly

### DISCUSSION THREAD

**Discussion by XXiaoA** [adityatelange/hugo-PaperMod#897] [Q&A]
Looking the top of my [Website](https://xxiaoa.github.io/) can find that **menu disappeared**
![Screenshot_2022-04-26-22-47-41-534_com mmbox xbrowser](https://user-images.githubusercontent.com/62557596/165328090-a65cf325-816b-4496-82d4-9d4bafeb5c00.jpg)

It was normal few days ago, but today it disappear suddenly but i don't do anything including my configuration. And how to solve it? Thx in advance 
 And here's my `config.yml` file

```
baseURL: "https://xxiaoa.github.io/"
title: XXiaoA's Blog
paginate: 5
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

permalinks:
  post: "/:year/:month/:day/:filename/"

minify:
  disableXML: true
  # minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: XXiaoA's Blog
  description: "My heart is with you"
  keywords: [Blog, XXiaoA, Daily, Programming]
  author: XXiaoA
  # author: ["Me", "You"] # multiple authors
  images: "<https://s2.loli.net/2022/02/13/LQZurKxEpmwolbD.jpg>"
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  comments: true

  label:
    text: "Home"
    # icon: /apple-touch-icon.png
    icon: https://s2.loli.net/2022/02/13/LQZurKxEpmwolbD.jpg
    iconHeight: 35


  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: email
      url: "mailto:isxxiaoa@gmail.com"
    - name: telegram
      url: "https://t.me/XXiaoA"
    - name: github
      url: "https://github.com/XXiaoA"
    - name: rss
      url: "https://xxiaoa.github.io/index.xml"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/xxiaoa/blog/tree/main/content"
    Text: " Edit" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
outputs:
  home:
      - HTML
      - RSS
      - JSON # is necessary

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: Archives
      url: archives/
      weight: 5
    - name: Categories
      url: categories/
      weight: 10
    - name: Tags
      url: tags/
      weight: 15
    - name: Search
      url: search/
      weight: 20
    - name: About
      url: about/
      weight: 25


```

**Comment by XXiaoA** [comment]
BTW the version of hugo is `0.97.3`

**Comment by adityatelange** [comment]
You found an Easter egg. Congratulations

**Reply by XXiaoA** [reply]
wow, how lucky i am😆 So how to make it  normal?

**Reply by adityatelange** [reply]
Move menu above params
And include fuseOpts inside params

**Reply by XXiaoA** [reply]
I have changed it but doesn't work. maybe it's a bug?
```yml
menu:
  main:
    - name: Archives
      url: archives/
      weight: 5
    - name: Categories
      url: categories/
      weight: 10
    - name: Tags
      url: tags/
      weight: 15
    - name: Search
      url: search/
      weight: 20
    - name: About
      url: about/
      weight: 25

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: XXiaoA's Blog
  description: "My heart is with you"
  keywords: [Blog, XXiaoA, Daily, Programming]
  author: XXiaoA
  # author: ["Me", "You"] # multiple authors
  images: "https://s2.loli.net/2022/02/13/LQZurKxEpmwolbD.jpg"
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  comments: true

  label:
    text: "Home"
    # icon: /apple-touch-icon.png
    icon: https://s2.loli.net/2022/02/13/LQZurKxEpmwolbD.jpg
    iconHeight: 35


  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: email
      url: "mailto:isxxiaoa@gmail.com"
    - name: telegram
      url: "https://t.me/XXiaoA"
    - name: github
      url: "https://github.com/XXiaoA"
    - name: rss
      url: "https://xxiaoa.github.io/index.xml"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/xxiaoa/blog/tree/main/content"
    Text: " Edit" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

```
