### DISCUSSION TITLE
is it possible to change the name of the language?

### DISCUSSION THREAD

**Discussion by tonyelpriulas** [adityatelange/hugo-PaperMod#921] [Q&A]
I am referring to this
![image](https://user-images.githubusercontent.com/77447552/169355929-336d3d08-c214-4561-a008-7e14983ece2f.png)
I don't want it to be the abbreviation of the language. I want the full word to appear

**Comment by RoneoOrg** [comment]
In `config.yml`, I have a setting "`languageName`", maybe?

```yml
languages:
    en:
        languageName: "English"
        weight: 1

    fr:
        languageName: "fr"
        languageAltTitle: French
```
