### DISCUSSION TITLE
Codeblock problems when show linenos

### DISCUSSION THREAD

**Discussion by JoJoJotarou** [adityatelange/hugo-PaperMod#922] [Ideas]
Related issues:
- [issue#695](https://github.com/adityatelange/hugo-PaperMod/issues/695)
- [issue#919](https://github.com/adityatelange/hugo-PaperMod/issues/919)
- [issue#697](https://github.com/adityatelange/hugo-PaperMod/pull/697)
- [#discussioncomment-2777192](https://github.com/adityatelange/hugo-PaperMod/discussions/525#discussioncomment-2777192)

**The problem occurs when you use highlight lines !!!**
**The text you see in the image is what I used in Markdown!!!**

I've had some tests recently.In [sample config.yml](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/#sample-configyml):

```yml
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
```

![](https://img1.imgtp.com/2022/05/21/lLBym1vS.png)

this
`````html
```html
```
`````
is same as this.
`````html
```html {linenos=table}
```
`````

html like:

```html
<div class="highlight">
    ...
    <table>
        <tbody>
            <tr><td><pre><code>......</code></pre></td></tr>
            <tr><td><pre><code>......</code></pre></td></tr>
        <tbody>
    </table>
    ...
</div>
```

**Means the codeblock is rendered as `<table>` by default.**

By https://gohugo.io/functions/highlight/#options
> Instead of specifying both lineNos and lineNumbersInTable, you can use the following shorthand notation:
>
> lineNos=inline
> equivalent to lineNos=true and lineNumbersInTable=false
> lineNos=table
> equivalent to lineNos=true and lineNumbersInTable=true

So add `lineNumbersInTable=false` in config.yml to tell Hugo not use `<table>` rendering codeblock.

```yml
markup:
    highlight:
        lineNumbersInTable: false
```
now, this
`````html
```html
```
`````
is same as this.
`````html
```html {linenos=inline}
```
`````

html like:

```html
<div class="highlight">
    <pre><code>......</code></pre>
    <pre><code>......</code></pre>
</div>
```

Then add this:
![](https://img1.imgtp.com/2022/05/20/ggWFWcSL.png)
```css
/* assets/css/extended/custom.css */
.post-content .highlight pre {
    margin: 0;
    background: var(--theme) !important;
}
```
Final effect：

![](https://img1.imgtp.com/2022/05/20/Z9wZOgLd.png)

Derivative problems:

![](https://img1.imgtp.com/2022/05/21/qsCTqwaD.png)

I haven't found a real solution, but it can be done:

```css
/* assets/css/extended/custom.css */
.post-content pre code {
    word-break: break-word;
}

.post-content .highlight pre code span{
    white-space: break-spaces;
}
```
![](https://img1.imgtp.com/2022/05/21/p9VigJoL.png)

hugo: v0.95
PaperMod(commit Id): [cb9be55c78efadee651f3a9f5e9b719f28a6d290](https://github.com/adityatelange/hugo-PaperMod/commit/cb9be55c78efadee651f3a9f5e9b719f28a6d290)
