### DISCUSSION TITLE
How do I set the favicon for my webpage

### DISCUSSION THREAD

**Discussion by keitng** [adityatelange/hugo-PaperMod#953] [Q&A] [answered]
I've tried putting favicon.ico into /static/favicon/ and adding 
`params:
     assets:
          favicon: "/static/favicon/favicon.ico"`

into config.yml but it still doesn't work. Help appreciated, thanks

**Comment by keitng** [comment]
Follow up:

I've adjusted the code in config.yml as following:
`params:
  homeInfoParams:
    Title: Hi
    Content: Sample text
assets:
  favicon: "/favicon.ico"
  favicon16x16:  "/favicon-16x16.png"
  favicon32x32:  "/favicon-32x32.png"
  apple_touch_icon:  "/apple-touch-icon.png"
  safari_pinned_tab:  "/safari-pinned-tab.svg"`

I've also put the favicon files in /static instead of /static/favicon

problem still persists.

**Reply by KarlEmilArvid** [reply]
Might be a little late but if someone else stumbles on this problem I managed to fix it by making a folder and placing the images there.
So it would look something like this `params: assets: favicon: "favicons/favicon.ico"`

**Reply by mapfumo** [reply]
That worked for me. Thanks.

**Reply by yimmy23** [reply]
I used the same method, but my website didn't work. Should I create the favicons folder in the root directory or in /static? How should I configure config.yml? It would be great if you could answer!

**Comment by adityatelange** [comment, marked as answer]
@keitng @KarlEmilArvid @perhapzz 

https://github.com/adityatelange/hugo-PaperMod/blob/be00e5a557212de1067016f0fe8a4aa00d23f2e2/config.yml#L171-L177

**Reply by adityatelange** [reply]
If `favicon.ico` is in `/static/assets/favicon.ico`, we put `favicon: "/assets/favicon.ico"`

**Reply by passmetheplay** [reply]
The favicon file must put in  statics/assets/ directory.  wired ..

**Reply by foegra** [reply]
glad i know now. Would be good to have better description in config file as comments

**Comment by perhapzz** [comment]
Thanks a lot!

**Comment by ile** [comment]
I have tried all the combinations for config.yml I can think of, but I can't make it find the favicon.

Favicon saved in (`hugo-PaperMod/`) `assets/images/favicon.ico`.

Tried:

```yml
params:
  assets:
    favicon: "images/favicon.ico"
```
```yml
params:
  assets:
    favicon: "/images/favicon.ico"
```
```yml
params:
  assets:
    favicon: "assets/images/favicon.ico"
```
```yml
params:
  assets:
    favicon: "/assets/images/favicon.ico"
```

@adityatelange

**Reply by mapfumo** [reply]
If remember correctly I had to name my file "favicon.png" and it worked. I also had to put the file in both "public/img/favicon.png" and "static/img/favicon.png". I am sure it doesn't have to in both directories.

params:
    assets:
       favicon: "/img/favicon.png"

**Reply by DG9Jww** [reply]
```yaml
  assets:
    disableHLJS: true
    favicon: "assets/favicon.ico"
```

Put ico file in static/assets/, then it works.

**Comment by AntonioBisconti** [comment]
Hi, i want to set a favicon for my website. I've used Hugo with PaperMod theme. I followed documentation to set it [FAQs Adding Custom Favicon(s)](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/) and I used [favicon.io](https://favicon.io/) to generate the files.  This is the directory structure:
![favicon](https://github.com/adityatelange/hugo-PaperMod/assets/142344308/d70bf56a-6130-4318-89a5-d6115948fab9)
As indicated on [favicon.io](https://favicon.io/), I also inserted these lines of code: 

```html  
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
   <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
   <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
   <link rel="manifest" href="/site.webmanifest">
```
under ~/Documenti/BLOG/layouts/partials/extend_head.html. and ~/Documenti/BLOG/themes/PaperMod/layouts/partials/extend_head.html . Despite this it doesn't work. I also followed this github discussion [How do I set the favicon for my webpage](https://github.com/adityatelange/hugo-PaperMod/discussions/953) , but nothing.
Thanks for your help!

**Comment by mapfumo** [comment]
Try looking at mine. mapfumo.github.io

**Comment by ch4r13** [comment]
If anyone have also problem, My issue dissapeared when I changed `favicon.ico` to `favicon.svg`, You should also have icon in this format of course.
```
hugo.yaml
-----------------
params:
  assets:
    favicon: "/assets/favicon.svg"

```

**Comment by cmd05** [comment]
It worked for me by specifying all the favicon icon sizes.

```yaml
params:
  assets:
    favicon: "assets/favicon.ico"
    favicon16x16: "assets/favicon.ico" 
    favicon32x32: "assets/favicon.ico" 
```

**Reply by pathare-blackduck** [reply]
What worked for me was adding my `favicon.svg` file into the project's `static` directory (not `assets`) - the `static` directory is at the root of the project.
Then, updating my `hugo.toml` to include:
```
[params.assets]
  favicon = "favicon.svg"
  favicon16x16 = "favicon.svg"
  favicon32x32 = "favicon.svg"
```
Not sure why it should be `params.assets` (instead of say, `params` or `params.static`) but that's what worked.

**Comment by boltsteel** [comment]
After some experimentation, I put my icons in ./static/icons, and configured like this in my yaml file, it worked:
```
params:
    assets:
       favicon: "/icons/favicon.ico"
       favicon16x16: "/icons/favicon-16x16.png" 
       favicon32x32: "/icons/favicon-32x32.png" 
       webmanifest: "/icons/webmanifest.json"
       apple_touch_icon: "/icons/apple-touch-icon.png"
```
