### DISCUSSION TITLE
Search page is inaccessible - returns 404

### DISCUSSION THREAD

**Discussion by mlazzarotto** [adityatelange/hugo-PaperMod#993] [General]
Hi, I'm configuring my Hugo (latest version) website in 2 languages: IT (primary) and EN.
I tried to configure the search like you did on the demo website, but every time i go to http://localhost:1313/search, I get a 404 error.

My structure is:
mlazzarotto.it/
  - config.yml
    - content/
    - search.md
    - search.en.md
    - italian/posts/
    - english/posts/

part of my config.yml
```
languages:
  it:
    title: Marco Lazzarotto
    description: "Have you tried turning it off an on again?"
    weight: 1
    contentDir: content/italian
    languageName: Italiano
    languageCode: it
    DateFormat: "2 Gennaio, 2006"
    copyright: E' tutto mio!
    menu:
      main:
        - name: Cerca
          url: /search/
          weight: 40
  en:
    title: Marco Lazzarotto
    description: "Have you tried turning it off an on again?"
    weight: 1
    contentDir: content/english
    languageName: English
    languageCode: en-us
    DateFormat: "January 2, 2006"
    copyright: It's all mine!
    menu:
      main:
        - name: Search
         # tried also without /en
          url: /en/search/
          weight: 40
```

my search.md file
```
---
title: "Cerca" # in any language you want
layout: "search" # is necessary
#url: "/cerca"
# description: "Description for Search"
#summary: "search"
#placeholder: "prova a digitare qualcosa"
---
```
my search.en.md file
```
---
title: "Search" # in any language you want
layout: "search" # is necessary
#url: "/en/search"
# description: "Description for Search"
#summary: "search"
#placeholder: "try typing something"
---
```
