### ISSUE TITLE
[feature request] taxonomies i18n complement

### ISSUE THREAD

**Issue by myodan** [adityatelange/hugo-PaperMod#1007]
It would be nice to add a setting for the language display in the taxonomies i18n.
for example, in Korean, tags are translated as "tags." When encoding the URL, it is written `%ed%83%9c%ea%b7%b8`, which is not good to see.
However, if you set it in English(ktag) there is no reason to set the i18n setting.

ex) config.yml
```
languages:
  en:
    taxonomies:
      - display: Categories
        key: categories
      - display: Tags
        key: tags
  ko:
    taxonomies:
      - display: 카테고리
        key: kcategories
      - display: 태그
        key: ktags
```
