### ISSUE TITLE
homeInfoParams.Title CSS issue?

### ISSUE THREAD

**Issue by semuserable** [adityatelange/hugo-PaperMod#102]
Noticed that some "long" letters got cut. Is this some css issue?
![image](https://user-images.githubusercontent.com/2175097/100921349-1afee680-34e5-11eb-9d83-cdb1db47e71e.png)

**Comment by adityatelange** [comment]
@semuserable will fix it, thanx for reporting :+1:

**Comment by adityatelange** [comment]
![image](https://user-images.githubusercontent.com/21258296/101066058-f1fd5500-35bb-11eb-8b93-3dbc6727359e.png)

@semuserable cannot reproduce this !
can you share link? or which browser ? or device.

**Comment by semuserable** [comment]
Interesting! I'm on Chrome Version 87.0.4280.88 (Official Build) (64-bit), Win10.

**Comment by adityatelange** [comment]
> Interesting! I'm on the latest Chrome Version 87.0.4280.88 (Official Build) (64-bit), Win10.

Gotcha! I'll debug for this on similar machine, meanwhile PRs are welcome :)

**Comment by kdkasad** [comment]
I can't reproduce the issue either.

Browser: Brave  
Version: `Brave: 1.17.73 Chromium: 87.0.4280.67 (Official Build) unknown (64-bit)`

**Comment by semuserable** [comment]
@kdkasad very interesting indeed. Just checked `Brave` Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit) - I have the same "bug". Maybe that's because of the values I use in my config?

Just in case, attaching the `config.yml`

```yml
baseURL: "http://example.org/"
theme: hugo-PaperMod
languageCode: "en-us"
title: test

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Tags
          url: tags/
          weight: 10
          
params:
    env: production
    homeInfoParams:
        Title: "Test: my, garden!"
        Content: "Hello"

    socialIcons:
        - name: twitter
          url: "https://test.com/"
        - name: stackoverflow
          url: "https://test.com/"
        - name: github
          url: "https://test.com/"
        - name: medium
          url: "https://test.com/"
        - name: linkedin
          url: "https://test.com/"

assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
```
