### ISSUE TITLE
Documentation: social icons can apparently have a title

### ISSUE THREAD

**Issue by RoneoOrg** [adityatelange/hugo-PaperMod#1032]
Hi there,

accessibility of Social Icons can be improved easily, as each of them can get a `title` specified, as we can see in [layouts/partials/social_icons](https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/social_icons.html#L3)

[This page of the wiki](https://github.com/adityatelange/hugo-PaperMod/wiki/Variables#socialicons) (and [this one](https://github.com/adityatelange/hugo-PaperMod/wiki/Icons#social-icons) too) should be updated accordingly:

### Before

```
socialIcons:
    - name: "<platform>"
        url: "<link>"
```

### After

```
socialIcons:
    - name: "<platform>"
        title: "The home page of platform.com"
        url: "<link>"
```

(Github wiki contribution is a pain BTW)

Cheers
