### ISSUE TITLE
Document "displayFullLangName"

### ISSUE THREAD

**Issue by RoneoOrg** [adityatelange/hugo-PaperMod#1034]
Hi there,

it's not documented, but it's possible to customize the language name this way:

Add in config.yml

```
params:
  displayFullLangName: true

languages:
      fr:
        languageName: "French"
```

I found no reference to `displayFullLangName` in the doc / wiki

Cheers
