### ISSUE TITLE
[Feature Request] Last Modified Date in post meta

### ISSUE THREAD

**Issue by kazettique** [adityatelange/hugo-PaperMod#1037]
Does we have any plan to add last modified date beside the create date in post meta?
As I know Hugo provides `.Lastmod` parameter from [Git info variables](https://gohugo.io/variables/git/)
It would be great to show the latest modified date on the post.

Thanks & cheers.

**Comment by miawithcode** [comment]
hi, I figure how to add last modified out, here is my solution.

1. config `config.yml` with: 
```
    enableGitInfo: true

    frontmatter:
        lastmod:
        - lastmod
        - :git
        - date
        - publishDate
```

2. add this to `layouts/partials/post_meta.html`

```
    {{- if not .Lastmod.IsZero -}}
    {{- $scratch.Add "meta" (slice (printf "<span title='%s'>updated %s</span>" (.Lastmod) (.Lastmod | time.Format (default "January 2, 2006" site.Params.DateFormat)))) }}
    {{- end }}
```

3. Then it is done. I hope it's working for you.
