### ISSUE TITLE
[BUG] Post Nav Links not appear in second menu

### ISSUE THREAD

**Issue by prish-collab** [adityatelange/hugo-PaperMod#1054]
**Describe the bug**
So I created two menus e.g blogs, short-posts by changing config.yml file as below.
```
    menu:
      main:
        - identifier: Blog
          name: Blog
          weight: 1
          url: /posts/
        - identifier: Learnings
          name: Learnings
          weight: 2
          url: /learnings/
```
Prev & next navigation links are working on pages in posts section but not on pages in learnings sections.

 - Hugo Version [ >=0.83.0 expected]: >=0.90.0
 - Theme Version [commit-id]: [3a0a4811](https://github.com/adityatelange/hugo-PaperMod/tree/3a0a4811cbc07c0bea09ef55b3c1bfb39b48cddd)

**Steps to reproduce the behavior:**

**Expected behavior**:

**Repo/Source where this issue can be reproduced**:

**Screenshots**
Expected Outcome in pages in posts sections - 
![image](https://user-images.githubusercontent.com/31505174/191950695-630c7c00-ff7b-48a7-a94f-6b4f69ab105d.png)
Outcome in pages in learnings sections
![image](https://user-images.githubusercontent.com/31505174/191951800-57ef0d65-3acd-4502-9d52-85b3148bbf43.png)

**Additional context**
