### ISSUE TITLE
[Feature Request] Option for different logo in dark/light mode

### ISSUE THREAD

**Issue by istvnurbn** [adityatelange/hugo-PaperMod#1063]
Hi,

Would it be possible to add a separate dark/light mode logo to the site?

I'm now using a [solution](https://push.blue/posts/20220718-add-lightdarklogoswap/) by @pushblue.

It is okay for now, but if there will be a major change in the header/footer partial this will cease to work.

My suggestion would be to add two separate icon params under the label group like so:

```YML
label:
  text: "my-title"
  iconDark: "my-darkmode-icon.svg"
  iconLight: "my-lightmode-icon.svg"
```
