### ISSUE TITLE
Image path not resolving on dev server and production

### ISSUE THREAD

**Issue by chlab** [adityatelange/hugo-PaperMod#1145]
Hi all

First of all, thanks for this great theme!
I've having some trouble getting cover images to work properly on posts. I can get it work locally on the dev server but not when deployed. I'm deploying to Gitlab pages but it doesn't matter because the local production build also doesn't seem correct. This is my setup:

config/_default/config.yml:
```
baseURL: ""
```

config/production/config.yml:
```
baseURL: "https://gitlab.io/path/to/project/"
```

content/:
```
content
└── posts
    └── 2023-01-31-initial-post
        ├── 2023-01-31-initial-post.md
        └── cover.png
```

2023-01-31-initial-post/2023-01-31-initial-post.md:
```
---
title: "Hello world"
date: 2023-01-31T11:11:30+01:00
cover:
    image: "/posts/2023-01-31-initial-post/cover.png"
    alt: "A neat cover image"
    relative: true # note: I also tried with relative: false
---
```

When I run `hexo server` the cover image loads, however, when I run `hexo` and take a look at the generated static files, it looks like this: 

public/posts/:
```
public/posts
├── 2023-01-31-initial-post
│   ├── 2023-01-31-initial-post
│   │   └── index.html
│   └── cover.png
├── index.html
└── index.xml
```

And the relevant html of 2023-01-31-initial-post/2023-01-31-initial-post/index.html:
```
<figure class="entry-cover"><img loading="lazy" src="https://gitlab.io/posts/2023-01-31-initial-post/cover.png" alt="A neat cover image">
```

Two things stand out to me:

* the cover.png file is one level higher than the index.html itself. This seems strange but shouldn't matter sind the relative path in the generated html looks correct
* the _/path/to/project/_ part of the production `baseUrl` is missing. This is the problem I guess.

Unfortunately, the documentation on the cover images is a bit vague on how exactly to configure `baseUrl `and `relative`. Am I missing something? Thank you for any help!

**Comment by chlab** [comment]
The problem was the leading / in the image path. This works both locally and on production:

```
---
title: "Hello world"
date: 2023-01-31T11:11:30+01:00
cover:
    image: "posts/2023-01-31-initial-post/cover.png"
    alt: "A neat cover image"
---
```

Cheers
