### ISSUE TITLE
[BUG] Search is not working, Error 404 index.json not found

### ISSUE THREAD

**Issue by cannox227** [adityatelange/hugo-PaperMod#1212]
**Describe the bug**
I am currently running my hugo website locally. I followed the wiki in order to setup the search page, however, **when I type into the search bar a part of the title of a post no one result is showed.** 

Running the page in dev mode I've been able to see that the problem could be linked to the fact that the `GET` function (located in `themes/PaperMod/assets/js/fastsearch.js`) that tries to get the `index.json` file (which is located in `themes/PaperMod/layouts/_default/index.json`) returns `Error 404`

Of course, I have verified that my post have the `searchHidden` flag set to false value.

**My env:**
 - Device/Os: MacOS 12.3.1
 - Type: Desktop
 - Browser and version: Chrome v. 101.0.4951.54
 - Hugo Version: hugo v0.111.3
 - Theme Version: master

**Steps to reproduce the behavior:**

1. Go to the search page
2. Try to type the first world of a title of a post 
3. Get no results

**Expected behavior**:

The page should give me back a results (the post I'm looking for).

**Repo/Source where this issue can be reproduced**:

Actually the code is running locally and it has not been uploaded yet on github, anyway I will do it if it will be necessary

**Screenshots**
<img width="376" alt="image" src="https://github.com/adityatelange/hugo-PaperMod/assets/33253895/ac4fb572-5bc3-46b0-a721-534b86edfb00">

> _The post I am looking for_ 

<img width="376" alt="image" src="https://github.com/adityatelange/hugo-PaperMod/assets/33253895/327b79f8-2b2b-44e9-bef3-be5e65eb2901">

> _The search page displaying no results_

<img width="453" alt="image" src="https://github.com/adityatelange/hugo-PaperMod/assets/33253895/ae56832f-b8e9-4c2b-8176-0e193d0f5a6b">

> _Error 404 when the search page tries to access to the index.json file_

<img width="550" alt="image" src="https://github.com/adityatelange/hugo-PaperMod/assets/33253895/305af5e8-cfb4-4dca-86d3-581af3246b4c">

> _The GET call, located at line 51 of `fastsearch.js`_

**Additional context**

My `config.yml` contains
````yaml
params:
  outputs:
      home:
        - HTML
        - RSS
        - JSON 
    # https://fusejs.io/api/options.html
    fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]
````
My `search.md`contains
````md
---
title: "Search" 
layout: "search" 
# url: "/archive"
# description: "Description for Search"
summary: "search"
placeholder: "placeholder text in search input box"
---
`````

How should I link the index.json file to the correct function? 
I have also tried to substitute the path with `"../../layouts/_default/index.json`, however I get the same error...
Do you have any solution?
