### ISSUE TITLE
Menu links with no trailing slash are broken

### ISSUE THREAD

**Issue by kdkasad** [adityatelange/hugo-PaperMod#123]
> > For example, on my website, I want a link to the RSS feed, which is located at `/blog/index.xml`. I set that as the URL for the menu item, but when generating, a slash (`/`) was appended, which turned it into `/blog/index.xml/`. This path is incorrect, and leads to a 404.
> 
> Haven't experienced this, try it on hugo's server command

I did. It has the same problem. Here's the relevant section of my `config.yaml`:
```
menu:
  main:
  - identifier: tags
    name: tags
    url: /tags/
    weight: 20
  - identifier: categories
    name: categories
    url: /categories/
    weight: 10
  - identifier: rss
    name: rss
    url: /index.xml
    weight: 30
  - identifier: search
    name: search
    url: /search/
    weight: 40
```

The `rss` menu entry will point to `/index.xml/`, when it should be `/index.xml`. When using the `hugo server` command, this isn't a problem, since it rewrites `/index.xml/` to `/index.xml`, however it is a problem on production web servers (e.g. apache or nginx).

_Originally posted by @kdkasad in https://github.com/adityatelange/hugo-PaperMod/pull/122#issuecomment-742722583_
