### ISSUE TITLE
[BUG] Chroma not rendering

### ISSUE THREAD

**Issue by ajossorioarana** [adityatelange/hugo-PaperMod#1241]
**Describe the bug**

 - Device/Os: Windows 10
 - Type: Desktop
 - Browser and version: Chrome 114.0
 - Hugo Version: 0.113
 - Theme Version: master

**Steps to reproduce the behavior:**
1. Follow [the FAQ](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#using-hugos-syntax-highlighter-chroma) to setup syntax-highlighting via Chroma.
2. Generate chroma stylesheet as commented on issues #901 and #1046, saved in "assets/css/extended/monokai.css"
3. Observe syntax-highlighting of code-snippet in served website

**Expected behavior**:
Code highlighting with chroma

**Repo/Source where this issue can be reproduced**:
[Repo with problem](https://github.com/ajossorioarana/ajossorioarana.github.io)

**Screenshots**
![image](https://github.com/adityatelange/hugo-PaperMod/assets/54476474/ab138825-325d-4f9c-9e4f-39f9ddbee3b4)

**Additional context**

Here's the relevant excerpt from my `config.yaml`:

```toml
 [params.assets]
  disableHLJS = true
# ...
[markup.highlight]
  noClasses = false
  # anchorLineNos = true
  codeFences = true
  guessSyntax = true
  # lineNos = true
  style = "monokai"
```
