### ISSUE TITLE
[BUG] wrong load stylesheet and JS on multihost (multilingual)

### ISSUE THREAD

**Issue by sunuazizrahayu** [adityatelange/hugo-PaperMod#126]
my config:
```
languages:
  id:
    baseURL: "site.com/id/"
    languageName: "Indonesia"
  en:
    baseURL: "site.com/en/"
    languageName: "English"
```
on preview of `hugo server`, second language (english) load stylesheet from first languange (indonesia).
it produce
![Capture](https://user-images.githubusercontent.com/18210880/101905502-268b9500-3bea-11eb-8ec0-df4dab3de360.PNG)
i think this config must use their own baseUrl.
so stylesheet must loaded as `http://site.com/en/my.css`, not `http://site.com/id/my.css`

---

Noted points:

1. <strike>Always uses 1st Language's (by alphabetical order) assets </strike>
