### ISSUE TITLE
Archive, search and tags link not appeared.

### ISSUE THREAD

**Issue by haemtee** [adityatelange/hugo-PaperMod#129]
here my content folder

```
├── archetypes
│   └── default.md
├── config.yml
├── content
│   ├── archive.md
│   ├── post
│   │   └── myfirst-post.md
│   └── search.md
```

archive.md

```
---
title: "Archive" # in any language you want
layout: "archives" # is necessary
url: "/archive"
summary: "archive"
---
```

search.md

```
---
title: "Search" # in any language you want
layout: "search" # is necessary
# url: "/archive"
summary: "search"
---

```

hugo version = Hugo Static Site Generator v0.79.0 linux/amd64 BuildDate: 2020-11-27T13:28:13Z

**Comment by kdkasad** [comment]
Do you mean they don't appear on the homepage? If so, that's because you must add the proper post types to the `mainsections` list. The default type for pages not in a subfolder (i.e. directly in the `content` folder) is `page`.

Here's an example:
```yaml
params:
  mainsections:
    - page
```

**Comment by haemtee** [comment]
yes, i mean it doesnt appear on header, i try input to url directly and it works.
i try like this in config.yml but still not working (link doest appear)
```
params:
  mainsections:
    - page
    - post
    - archive
    - search
```
i also already add this code to bottom of config.yml
```
outputs:
  home:
    - HTML
    - RSS
    - JSON
```

**Comment by kdkasad** [comment]
> i mean it doesnt appear on header

So it sounds like you want to create menu entries for those links. Here's a sample menu section for your `config.yaml`:
```yaml
menu:
  main:
  - identifier: tags
    name: tags
    url: /tags/
    weight: 20
  - identifier: categories
    name: categories
    url: /categories/
    weight: 10
  - identifier: archive
    name: archive
    url: /archive/
    weight: 30
  - identifier: search
    name: search
    url: /search/
    weight: 40
```

@adityatelange I looked through the documentation on the example site and menus don't seem to be on there anywhere, even in the sample `config.yaml` file. Maybe that should be mentioned, or at least a link to the Hugo wiki entry on menus.
