### ISSUE TITLE
Why theme transition in order?

### ISSUE THREAD

**Issue by rea1shane** [adityatelange/hugo-PaperMod#1326]
I want to add delay when theme transition, I add these CSS:

```css
* {
    transition: color 200ms ease-in-out, background 200ms ease-in-out;
}
```

But I noticed that the color transitions of the elements are not simultaneous, but sequential, why?

And I found https://github.com/adityatelange/hugo-PaperMod/pull/407, is it the best way to do this thing? It modifies a lot of files and I want to as few as possible.
