### ISSUE TITLE
Recommendation for tweaking search options

### ISSUE THREAD

**Issue by dharmeshgordhan** [adityatelange/hugo-PaperMod#134]
I was implementing a search myself - then whoa - it showed up in PaperMod <3 

Anyways... I somewhat new to hugo - so not sure on the appropriate ways to tweak themes. Do you have any recommendations for how I can tweak the fuse search options? I wanted to search further than [100 characters](https://github.com/adityatelange/hugo-PaperMod/blob/master/assets/js/fastsearch.js#L16) (or - set [`ignoreLocation: true`](https://fusejs.io/api/options.html#ignorelocation)) so I can search a larger portion of my content.

Cheers

**Comment by adityatelange** [comment]
@dharmeshgordhan you may refer to https://fusejs.io/api/options.html and use [thi](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-how-to/#override-theme-template) to override https://github.com/adityatelange/hugo-PaperMod/blob/master/assets/js/fastsearch.js 
so that you can achieve that what you want.

Also thank you for appreciation :D

**Comment by adityatelange** [comment]
I have added a config param so that you can customize options
 
basic usage is shown below 

in config.yml, add fuseOpts as shown below =>
```yml
  params:
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
```
