### ISSUE TITLE
`cover.hidden` being ignored in page variables

### ISSUE THREAD

**Issue by nicolaiarocci** [adityatelange/hugo-PaperMod#1367]
config.yml:

```
  cover:
    hidden: true 
    hiddenInList: false
    hiddenInSingle: true
```

in page file:

```
---
title: Speaking
share: false
weight: 8
cover:
    image: images/speaking.png
    hidden: false
---
```

WIth the above, the Speaking page shows no cover. If I set `hiddenInSingle: false`, then the cover appears in the page. It appears that the page variable is being ignored.

```
$ hugo version
hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended darwin/arm64 BuildDate=2023-12-08T08:47:45Z VendorInfo=brew
```

theme version: master branch
browser: Safari latest
OS: macOS

**Comment by adityatelange** [comment]
can you update to latest commit? i think it's patched recently.

**Comment by nicolaiarocci** [comment]
On today's master:

```
  cover:
    hidden: true 
    hiddenInList: false
    hiddenInSingle: true
```

in page file:
```
---
title: Speaking
share: false
weight: 8
cover:
    image: images/speaking.png
    hidden: false
---
```

Doesn't show the cover on the page.

**Comment by adityatelange** [comment]
https://github.com/adityatelange/hugo-PaperMod/blob/71ce72b1bfb868b406c369c958f8682c63940e01/layouts/_default/single.html#L32

> The Param method on a Page object looks for the given KEY in page parameters, and returns the corresponding value. If it cannot find the KEY in page parameters, it looks for the KEY in site parameters. If it cannot find the KEY in either location, the Param method returns nil. [^1]

[^1]: https://gohugo.io/methods/page/param/#:~:text=The%20Param%20method%20on%20a%20Page%20object%20looks%20for%20the%20given%20KEY%20in%20page%20parameters%2C%20and%20returns%20the%20corresponding%20value.%20If%20it%20cannot%20find%20the%20KEY%20in%20page%20parameters%2C%20it%20looks%20for%20the%20KEY%20in%20site%20parameters.%20If%20it%20cannot%20find%20the%20KEY%20in%20either%20location%2C%20the%20Param%20method%20returns%20nil.



If you do not mention `hiddenInSingle` in page it will check if `hiddenInSingle` is set in site, if not it will fallback to `hidden`.
I see you have `hiddenInSingle` set in site so it never reaches `hidden` for page/site.

**Comment by nicolaiarocci** [comment]
Thanks for getting back to me. 

I just tried the following:

Site params:
```
params:
  cover:
    hidden: true
    hiddenInList: false
    hiddenInSingle: true
```

As one would expect covers don't show in single pages. 

Then, I updated a single post like this:
```
---
cover:
    image: images/the-boy-and-the-heron.jpg
    hidden: false
---
```

But the cover image doesn't show up on that page. It's not a big deal as I'm fine with showing cover images where they're set (`hiddenInSingle: false` in site params), but I'd like to get understand how it all works (and it looks super-simple, I'm probably being dumb.)
