### ISSUE TITLE
Wiki docs: Incorrect YAML Sample in Wiki

### ISSUE THREAD

**Issue by tk-zzz** [adityatelange/hugo-PaperMod#1396]
I've observed that there is an indentation issue within the buttons section, where the second button's properties are not properly indented. I kindly request that this be addressed at your earliest convenience.

https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode

```
params:
    profileMode:
        enabled: true
        title: "<Title>" # optional default will be site title
        subtitle: "This is subtitle"
        imageUrl: "<image link>" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
            url: "/archive" # here
            - name: Github
            url: "https://github.com/" #here

    socialIcons: # optional
        - name: "<platform>"
            url: "<link>"
        - name: "<platform 2>"
            url: "<link2>"
```
