### ISSUE TITLE
[Feature] Allow setting favicon path in config file

### ISSUE THREAD

**Issue by singhkays** [adityatelange/hugo-PaperMod#14]
Can I set a custom path to favicon? In another theme 'minimo' (https://themes.gohugo.io/minimo/) I was able to specify the following

```toml
[params.assets]
favicon = "img/terminal.ico"
customCSS = ["css/custom.css"]
```
