### ISSUE TITLE
[BUG] Images quality was degraded

### ISSUE THREAD

**Issue by DG9Jww** [adityatelange/hugo-PaperMod#1436]
- Device/Os: Win11
 - Type: Desktop
 - Browser and version: Chrome
 - Hugo Version: hugo v0.122
 - Theme Version: latest

I just downloaded the [example site codes](https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite). Then I enabled the profile mode and change the profile image, but the images quality was degrade. I've tried several images. I didn't change any codes, just the image url.

Related config codes:
```yml
  profileMode:
    enabled: true
    title: PaperMod
    imageUrl: "images/222.png"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags
```

![image](https://github.com/adityatelange/hugo-PaperMod/assets/84201009/74563903-db59-4894-b010-55568a435f38)
![image](https://github.com/adityatelange/hugo-PaperMod/assets/84201009/a6533a36-7536-4203-a30e-197cd9d7f6a9)
