### ISSUE TITLE
Support adding Link to footer for Privacy Policy or Footer

### ISSUE THREAD

**Issue by besendorf** [adityatelange/hugo-PaperMod#1481]
I think it would be a nice feature if I could change the footer text without overwriting the themes footer.html in the config to add a link for a privacy policy or an imprint or similar legally required information.

**Comment by adityatelange** [comment]
Hi @besendorf, added the following config opts. Kindly pull latest commit and let me know things works as intended.

```
params:
  footer:
    text: "This is footer text - markdown suported"
    hideCopyright: true
```
