### ISSUE TITLE
[BUG] menus not rendered in recent hugo versions, starting with 0.125.0

### ISSUE THREAD

**Issue by Cephra** [adityatelange/hugo-PaperMod#1505]
Starting with hugo version 0.125.0, the menus in my blog aren't rendered unless I explicitly add the menu to the .md file.
Here's a commit where I've fixed that in my blog: 
https://github.com/Cephra/blog/commit/c43764c5917ada29fc043e3dfa4851a7708bf6cb

 - Hugo Version [ >=0.112.4 expected]: v0.125.4+extended
 - Theme Version [e.g. v4.0, master, or commit-id ]: latest

1. Have a section in content such as /about or even simply search.md 
2. Render the blog
3. Visit the blog
4. about and search are not showing up in the menu.

With my local hugo installation (hugo v0.123.7+extended), everything works as expected.
The menu items are rendered.

https://github.com/Cephra/blog

With recent hugo:
![Screenshot_20240502_235403](https://github.com/adityatelange/hugo-PaperMod/assets/7629358/19787479-c922-41ce-be70-4fb8ca4e9f0e)

With old hugo:
![image](https://github.com/adityatelange/hugo-PaperMod/assets/7629358/4499abef-6457-4ae5-a393-7682fe2d9854)

As you can see, the menu isn't rendered.

**Comment by adityatelange** [comment]
Can't reproduce this issue. See generator meta tag https://adityatelange.github.io/hugo-PaperMod/

![image](https://github.com/adityatelange/hugo-PaperMod/assets/21258296/25220bb3-a678-4362-a926-6754cd33c72e)

**Comment by Cephra** [comment]
@adityatelange I've looked into the issue a bit more. It seems that the reason why the menu is rendering in the example site is this:

```yaml
languages:
  en:
# ...
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: WiKi
          url: https://github.com/adityatelange/hugo-PaperMod/wiki/
```

I didn't put any translations in my toml and thus I'm relying on hugos internal menu generation.

Once I remove those translations in the exampleSite, I can reproduce the issue. 

Now I wonder, is this actually an issue and if so, is it related to hugo or paperMod?

Maybe you can help!

Thanks,

Chris
