### ISSUE TITLE
[BUG]One file generates two pages and is duplicated in categories, tags and archives.

### ISSUE THREAD

**Issue by note4** [adityatelange/hugo-PaperMod#1569]
问题之前在 hugo 发布过，后来发现只是在 papermod 有该问题，其他主题没有这样的问题。
The problem was previously posted at hugo, and then it turned out that it was only at papermod that had the problem, and that other themes did not have such a problem.

hugo issues

<https://github.com/gohugoio/hugo/issues/12685>

![image](https://github.com/user-attachments/assets/c9b448df-106e-4105-9d20-101a96b7cd6e)

一个文件生成两个页面，并且在分类、标签和归档中重复出现。
One file generates two pages and is duplicated in categories, tags and archives.

内容会自动重复生成，且路径不同，如果配置了 url 就会有路径和内容一样的两个页面。config.yml配置如下：

The content will be automatically duplicated sheng generation, and the path is different, if you configure the url will have the same path and content of the two pages. config.yml configuration is as follows:

```

defaultContentLanguage: zh
defaultContentLanguageInSubdir: false

taxonomies:
  category: categories
  tag: tags
  series: series

permalinks:
  posts: "/log/:filename/"
  categories: "/:slug/"
  tags: "/tags/:slug/"
  series: "/series/:slug/"
  
languages:
  zh:
    languageName: "中文"
    weight: 1
    contentDir: "content/zh"
```

文件路径如下：
The file path is as follows:
![image](https://github.com/user-attachments/assets/68ee4d18-0d48-414c-b273-4a11c8484b8b)

hugo version

<pre>
$ hugo version
hugo v0.121.1+extended darwin/amd64 BuildDate=unknown VendorInfo=macports
</pre>
