### ISSUE TITLE
[Enhancement]:  problem multilingual solved

### ISSUE THREAD

**Issue by taf-neutrino** [adityatelange/hugo-PaperMod#1585]
### What you'd like to propose?

|                   |          |
| ----------------- | -------- |
| Hugo version:     | v0.133.0 |
| PaperMod release: | 7.0      |

## [solved] First problem, multilingual menu breadcrumbs.

Example path of file sistem: `/content/articles`

Configuration `hugo.yaml`

``````yaml
...
languages:
    en:  
        permalinks:
        page:
            articles: /articles/:slug/
        section:
            articles: /articles/
        menu:
            main:
                - name: Articles
                url: articles/
    it:
        permalinks:
        page:
            articles: /articoli/:slug/
        section:
            articles: /articoli/
        menu:
            main:
                - name: Articoli
                url: articoli/
...
``````

The problem is found in **breadcrumbs**, if you use only one language works correctly.
I modified the file `/layouts/partials/breadcrumbs.html` with the code I attach.

```htm
{{- if (.Param "ShowBreadCrumbs") -}}
<div class="breadcrumbs">
    {{- range .Ancestors.Reverse }}
    <a href="{{ .RelPermalink }}">{{ if .IsHome }}{{ i18n "home" }}{{ else }}{{ print "&nbsp;»&nbsp;" | safeHTML }}{{ .Title }}{{ end }}</a>    
    {{- end -}}
</div>
{{- end -}}
```

## [solved] Second problem, translation tag page.

Configuration `hugo.yaml`

``````yaml
...
languages:
    en:
        taxonomies:
        tag: tags
    it:
        taxonomies:
        tag: etichette
...
``````

For **tags** page the problem is present for other languages, the data are not shown.

The solution:

``````html
# i18n/en.yaml
- id: tag
  translation: "tags"

# i18n/it.yaml  
- id: tag
  translation: "etichette"
``````
I've changed row number 46 `/layouts/_default/single.html`

``````html
    <!-- original code -->
    {{- $tags := .Language.Params.Taxonomies.tag | default "tags" }}
    <!-- code modified -->
    {{- $tags := .Language.Params.Taxonomies.tag | default | i18n "tag" }}
``````

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
