### ISSUE TITLE
[Bug] #156 doesn't work, images still appear as cover

### ISSUE THREAD

**Issue by bee-san** [adityatelange/hugo-PaperMod#164]
Referencing issue #156 which was fixed by https://github.com/adityatelange/hugo-PaperMod/commit/c9fa6c7915d275cbef1739a5b919e014e18ccb98

This doesn't work, for me :-( 

In `config.yaml`:

```
params:
    cover:
            hidden: true # hide everywhere but not in structured data
            hiddenInList: true # hide on list pages and home
            hiddenInSingle: true # hide on single page
```

In main page:
![image](https://user-images.githubusercontent.com/10378052/103431616-dbeab080-4bca-11eb-883b-4a66729b3d12.png)

On blog post:
![image](https://user-images.githubusercontent.com/10378052/103431618-e1e09180-4bca-11eb-8a45-ff0f0ca3ce3e.png)

When adding `hidden: true` to the blog posts front matter, it doesn't change anything :( 

I am on the latest version of `hugo-Papermod` (I git pull and there's nothing to pull) and I still get this.
