### ISSUE TITLE
Lists of mainSections render empty (Blank homepage and archive page)

### ISSUE THREAD

**Issue by thedivtagguy** [adityatelange/hugo-PaperMod#166]
This was working fine till yesterday, but today I ran it on the hugo-server and the homepage has become completely blank: 

![image](https://user-images.githubusercontent.com/6006888/103450189-ac29ce80-4cd8-11eb-83ef-82f43eedcfaf.png)

This is also the case with the archives page. You can see the live deploy here: https://thedivtagguy.netlify.app/

The only modifications I've made since last night is adding a new content-type, `projects` and copying the contents of `list.html` for posts into a new layout. The theme layouts themselves haven't been modified. The contents of my `config.yaml` are as follows: 

I've uploaded my website to this repo: https://github.com/thedivtagguy/website2 if this helps. 

What can I do to fix this?
```
baseURL: "http://thedivtagguy.netlify.app"
title: "thedivtagguy"
paginate: 8
theme: ["hugo-PaperMod", "hugo-shortcode-gallery"]
enableInlineShortcodes: true
enableRobotsTXT: true
label.icon: true

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Blog
                  url: archive
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Photography
                  url: photography/
                  weight: 6
                - name: Projects
                  url: /projects
                  weight: 7
   
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Aman Bhargava | Visual Artist"
    author: Aman Bhargava
    # author: ["Me", "You"] # multiple authors
    ShowReadingTime: true
    defaultTheme: auto
    ShowShareButtons: true
    displayFullLangName: true
    # images: ""
    # assets:
    #   favicon: '<path / external url>'

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "A Whole Sort of General Mishmash"
        Content: >
           Art and Code by Aman Bhargava
    socialIcons:
        - name: twitter
          url: "https://twitter.com/thedivtagguy"
        - name: instagram
          url: "https://instagram.com/thedivtagguy"
        - name: github
          url: "https://github.com/thedivtagguy"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/14425671/aman"
taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
 ```
