### ISSUE TITLE
[Bug]: Language emoji does not work vol2

### ISSUE THREAD

**Issue by Blintmester** [adityatelange/hugo-PaperMod#1667]
### What happened?

Same thing described here: https://github.com/adityatelange/hugo-PaperMod/issues/1640

The emoji flag is set as title and the language as the inner text in the anchor. This produce that in the web the button has the `:hu:` text.

### Steps to reproduce

Add this to `config.yaml`

```yaml
languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      tag: tags
      category: categories
hu:
    languageName: ":hu:"
    weight: 1
    taxonomies:
      tag: tags
      category: categories
```

### Hugo Version

Hugo >= 0.125.7 (Recommended - Minimum version required for PaperMod)

### PaperMod Version

https://github.com/adityatelange/hugo-PaperMod/commit/9f1f414be805a2f94e2f51bd4be2b365ff12386d

### Relevant log output

```shell
no logs
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
