### ISSUE TITLE
[Enhancement]: home info content would be in a separated markdown page and CSS rendered as a regular page

### ISSUE THREAD

**Issue by vepain** [adityatelange/hugo-PaperMod#1670]
## Wanted feature

* Move the home-info profile content from the Hugo config file (`hugo.yaml` or `hugo.toml`) to a regular markdown file (let say `content/home-info.md`) 
* Render the home info content as a regular page (reuse `.post-single.css`)

## Why this feature?

In home-info mode, if you test the following:

`hugo.yaml`
```yaml
params:
  description: "The description."
  author: Me

  defaultTheme: auto # to switch between dark or light according to browser theme
  env: production

  homeInfoParams:
    Title: Welcome
    Content: >
      First line.

      * First bullet point

      * Second bullet point
      * Third bullet point

      Last line 
```
You will obtain this rendering: 

![Image](https://github.com/user-attachments/assets/1eff6c4c-d4c1-4b4b-925a-c6df2ad555ba)

You can remark that:

* The bullets are not rendered for the list items
* You must add a new line to separate correctly the list items
* The last line is not considered as a new line, and is merged with the last list item.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
