### ISSUE TITLE
[Feature] Can you set  caption for cover image?

### ISSUE THREAD

**Issue by singhkays** [adityatelange/hugo-PaperMod#17]
I'd like to set the following caption for the cover image 

```html
<span style="margin:-20 0 0 0; display:block; text-align: center;"><i><small>Photo by <a href="https://unsplash.com/@birminghammuseumstrust?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Birmingham Museums Trust</a> on <a href="https://unsplash.com/?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></small></i></span>
```

Here's an example from another theme - https://minimo.netlify.app/docs/cover-image/

```yaml
---
cover:
  image: /images/eden-farm-children-s-village.jpg
  alternate: Picture of a yellow wall with a blue window in the upper-left corner
  caption: Eden Farm Children's Village by Gareth Harper on Unsplash
  style: full
---
```
