### ISSUE TITLE
ShowReadingTime in Bahasa Indonesia is broken

### ISSUE THREAD

**Issue by snydez** [adityatelange/hugo-PaperMod#172]
Hi there,
When I set `defaultContentLanguage: id`  and `ShowReadingTime: true`  the display is broken.
While if I didn't set `defaultContentLanguage`, things are ok.

![image](https://user-images.githubusercontent.com/2133889/104143827-9f515d00-53f3-11eb-8be9-ce50d38bbbe7.png)

**Comment by muhammadhanif** [comment]
Create `id.yaml` file and save it in `themes/hugo-PaperMod/i18n/`:

```
- id: prev_page
  translation: "Halaman Sebelumnya"

- id: next_page
  translation: "Halaman Selanjutnya"

- id: read_time
  translation:
    one : "1 menit"
    other: "{{ .Count }} menit"

- id: toc
  translation: "Daftar Isi"

- id: translations
  translation: "Terjemahan"
```
