### ISSUE TITLE
Image in Home-Info mode?

### ISSUE THREAD

**Issue by dictvm** [adityatelange/hugo-PaperMod#216]
I just stumbled upon this beautiful theme. However, just one suggestion: Would it be possible to display a picture in the Home-Info mode? Profile-Mode is missing a 2nd field for a bit of a description which Home-info brings but it's lacking the option of having a nice image above it the way Profile-mode does.

**Comment by bennesp** [comment]
For what concern the profile-mode, even if I cannot find in the documentation, there exists `subtitle`, as you can see here

https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/index_profile.html#L7

You can use it like this in `config.yaml`:

```yaml
params:
  profileMode:
    enabled: true
    title: "Example"
    subtitle: "This string will be shown as a description, under the title"
```
