### ISSUE TITLE
How to use ShowPostNavLinks?

### ISSUE THREAD

**Issue by kbc8894** [adityatelange/hugo-PaperMod#221]
Hello, I use user theme for my blog.
I try to enable prev, next button.
and I found this option.
```yml
params:
    ShowPostNavLinks: true
```
but, it doesn't working in my blog.
what can I do to enable like your page.
https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/
thanks.
regards

**Comment by adityatelange** [comment]
We have only added `ShowPostNavLinks: true` in config for https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/
see here => 4b1dce0c2f5a4c576364feda3be69584a5d1276a

**Comment by kdkasad** [comment]
Setting the option in `config.yml` works for me, too. @kbc8894 can you post the rest of your config? There's not much info for us to use to help you.

**Comment by kbc8894** [comment]
my config.yaml is below.
```yml
baseURL: "/"
languageCode: "en-us"
title: "ColdBottle"
theme: "PaperMod"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  homeInfoParams:
      Title: "ColdBottle"
      Content: 안녕하세요.
  ShowShareButtons: true
  ShowPostNavLinks: true
  comments: true
  assets:
      disableFingerprinting: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
menu:
    main:
        - identifier: archives
          name: Archives
          url: archives
          weight: 5
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 10
        - identifier: search
          name: Search
          url: search/
          weight: 20


taxonomies:
  category: categories
  tag: tags
  series: series
```
