### ISSUE TITLE
Home-Info Mode gives blank page

### ISSUE THREAD

**Issue by everetr** [adityatelange/hugo-PaperMod#227]
I tried the "master" branch as of now, v3.0, and v4.0. My Hugo version is "v0.80.0/extended linux/amd64 BuildDate: unknown". Manjaro Linux. **Edit:** I'm having the same issue with Regular Mode. Only Profile Mode works as expected. Same issue on Windows. Same with Hugo 0.74.0.

`config.yml`:

```yml
theme: PaperMod
params:
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about... 
```

Then I run `hugo server -D` but all I ever see is a blank page:

![image](https://user-images.githubusercontent.com/9023041/107453848-bfbb2700-6b19-11eb-89c3-e5bf1a1b2cae.png)
