### ISSUE TITLE
[Question] How to achieve non-blog-post pages

### ISSUE THREAD

**Issue by LarsEckart** [adityatelange/hugo-PaperMod#26]
Hello,

I really like this theme. One thing I haven't figured out yet though is how I can create "normal pages" like you have for example at https://adityatelange.tk/about/.

What I've done
`hugo new about.md`
and then in config.yaml
```
menu:
  main:
    - name: Archives
      url: /archives/
      weight: 10
    - name: About
      url: /about/
      weight: 15
```
but the resulting page starts like a blog post:

# About  [draft]
## October 6, 2020 · 0 min · Lars Eckart

I don't want a publish date or author for this article.

Any hints on how to achieve this?

**Comment by adityatelange** [comment]
I have to improve documentation  :P 
Do read this post: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/

---
About your doubt..
you can do that easily, make sure your directory structure is:
```tree
├── content/
│   ├── about.md
│   ├── archive.md
│   └── posts/
├── themes/
│   └── hugo-PaperMod/
└── config.yml
```
---

To hide`publish date or author`

```yml
---
title : "About"
hidemeta : true
comments : false #optional
---
```
