### ISSUE TITLE
The social icon of email cannot be linked to email

### ISSUE THREAD

**Issue by zincnode** [adityatelange/hugo-PaperMod#268]
Hi,
When I link to email through social icons, the hyperlink becomes **https://mydomain/email-address**,  404 error will appear after clicking. I came up with a solution. We can use [mailto](https://css-tricks.com/snippets/html/mailto-links/) in HTML to call up the default email program directly, and use the preset email address as the receiving address.

**Comment by adityatelange** [comment]
I cannot reproduce the issue

try using following format

```yml
    socialIcons:
        - name: email
          url: "mailto:me@examplesite.com"
```
