### ISSUE TITLE
[Feature] Support word wrap on code fragments

### ISSUE THREAD

**Issue by singhkays** [adityatelange/hugo-PaperMod#28]
I have some code fragments that require horizontal scrolling. However, I tried the solution here https://stackoverflow.com/a/56469907 and got wrapping to work. Can this be implemented by default or at least a user settable property in config file? 

```css
code {
  white-space : pre-wrap !important;
}
```
