### ISSUE TITLE
Social Icons not rendering in Safari

### ISSUE THREAD

**Issue by joeldeleep** [adityatelange/hugo-PaperMod#283]
I am running the latest papermod theme and gohugo. But the social icons are not rendered in Safari but at the same time it is rendered in Chrome and Firefox. 
```yml
baseURL: "https://example.com"
title: test
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Test
    description: ""
    author: world
    images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: dark # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    disableSpecial1stPost: false
    comments: false
    hidemeta: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Hello World
        subtitle: ""
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: blog
              url: posts
    # home-info mode
    homeInfoParams:
        Title: ""
        Content: 

    socialIcons:
        - name: twitter
          url: "https://twitter.com/username"
        - name: stackoverflow
          url: "https://stackoverflow.com/username"
        - name: github
          url: "https://github.com/username"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: categories
          name: Me 
          url: /about/
          weight: 10
        - identifier: tags
          name: test
          url: /test/
          weight: 20
```
