### ISSUE TITLE
.Site.Params.label.icon not rendering in post page

### ISSUE THREAD

**Issue by joeldeleep** [adityatelange/hugo-PaperMod#295]
I have the following params in config.yaml
```yaml
label:
        text: "My Blog"
        icon: logo.png
```

The icon is rendered on the home page but it is not rendered on the posts page.
Home Page
![home](https://user-images.githubusercontent.com/42582155/110245671-3963fa80-7f8a-11eb-9d52-8e9546e80ba7.png)

Post Page
![posts](https://user-images.githubusercontent.com/42582155/110245675-3ff27200-7f8a-11eb-960d-f457e96cb0af.png)

I have tried this in both Chrome and Safari which ended up with the same issue.
