### ISSUE TITLE
Cover Image Visible on Taxonomy pages even though cover.hiddenInList is set to True. [BUG]

### ISSUE THREAD

**Issue by cryptic-code** [adityatelange/hugo-PaperMod#341]
Cover image stays visible on taxonomy pages (like of a specific category) even though `cover.hiddenInList` is set to `True` in `config.yml`.

My current setting:
```yml
    cover:
        responsiveImages: true
        hidden: false # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page
```
