### ISSUE TITLE
[BUG] Incorrect internationalization

### ISSUE THREAD

**Issue by heyuanchao** [adityatelange/hugo-PaperMod#373]
**Describe the bug**

 - Device/Os: [Win 10]
 - Type: [Desktop]
 - Browser and version [Chrome 90.0.4430.72]:
 - Hugo Version [0.82]:
 - Theme Version [master]:

**Steps to reproduce the behavior:**

1. Add the following configuration into config.yml
```
    zh:
      languageName: "中文"
      weight: 4
      menu:
        main:
          - name: 文章
            url: archives
            weight: 5
          - name: 搜索
            url: search/
            weight: 10
          - name: 标签
            url: tags/
            weight: 10
          - name: 分类
            url: categories/
            weight: 10
```
2. click on '中文' - '分类' or '中文' - '标签'
3. you will see the bug

**Expected behavior**:

**Screenshots**

![image](https://user-images.githubusercontent.com/10580354/115359862-ab6a6900-a1f1-11eb-9414-e0bcaa0efd61.png)
![image](https://user-images.githubusercontent.com/10580354/115359925-b91fee80-a1f1-11eb-9a20-765a68b75324.png)
