### ISSUE TITLE
[Feature Request] Add icon support for menu items

### ISSUE THREAD

**Issue by miynat** [adityatelange/hugo-PaperMod#420]
Is it possible to add icon support for the elements on the top menu please?

**Comment by adityatelange** [comment]
@miynat You can now add icons to menu items via external scripts such as fontawesome

refer this https://gohugo.io/content-management/menus/#params to know how to add icons

---

using [fontawesome](https://fontawesome.com/v5.15/how-to-use/customizing-wordpress/snippets/setup-cdn-webfont#load-all-styles) menu icons should look like this when used with `pre` param
![image](https://user-images.githubusercontent.com/21258296/121695766-febdb100-cae8-11eb-8a28-f2f5af2ac363.png)

**Comment by miynat** [comment]
@adityatelange As far as I can see, Feather icons is used on the home page:

![image](https://user-images.githubusercontent.com/1431760/121801921-7a7f4100-cc42-11eb-9f6c-a1dc6eb445ab.png)

Is it possible to use them on the top menu as well?

That way, icons will have a consistent look all around the theme, and it will prevent users using another external resource (Font Awesome).

**Comment by loganmarchione** [comment]
@miynat see [this post](https://github.com/adityatelange/hugo-PaperMod/discussions/445) for an answer

**Comment by rickeygong** [comment]
### Add icons to the menu bar

Here, I am using icons from the FontAwesome family.

1. Visit [FontAwesome](https://fontawesome.com/) 

2. On the FontAwesome homepage, click the [Start for Free] button.

3. Enter your email address, click the [Send Kit Embed Code] button, and follow the prompts to register.

4. Then get a line of `script` embedded code.

5. Copy the `extend_head.html` file from the theme folder (`themes/paperMod/layouts/partials`) to the `themes/paperMod/layouts/partials` folder under the root directory, and paste the `script` provided by `FontAwesome` into it. provided by `FontAwesome` and paste in the `script` provided by `FontAwesome`.

```html
{{- /* Head custom content area start */ -}}
{{- /*     Insert any custom code (web-analytics, resources, etc.) - it will appear in the <head></head> section of every page. */ -}}
{{- /*     Can be overwritten by partial with the same name in the global layouts. */ -}}
{{- /* Head custom content area end */ -}}

<!-- Introducing FontAwesome icons -->
<script src="https://kit.fontawesome.com/xxxxxx.js" crossorigin="anonymous"></script>
```

6.Modify `menu.main` in the `hugo.yaml` configuration file ref:

``` yaml
menu:
      main:
        - identifier: search
          name: ' Search'
          url: /search/
          pre: '<i class="fa-solid fa-magnifying-glass"></i>'
          weight: 1
        - identifier: posts
          name: ' Posts'
          url: /posts/
          pre: '<i class="fa-solid fa-newspaper"></i>'
          weight: 2
```
