### ISSUE TITLE
[BUG] Using imageURL for profileMode preloads it on every page

### ISSUE THREAD

**Issue by danielfdickinson** [adityatelange/hugo-PaperMod#494]
Introduced in a86abf59947645d34c56ca31f6b94bcb99eeb750
Will be adding PR that resolves the issue shortly.

Device: Windows 10 Desktop (at least)
Browser: (New) Edge, Firefox, Chrome, latest stable versions as of 2021-08-09
Hugo Version (not relevant, but 0.85.0 through 0.87.0, at least)
PaperMod verision: 664299cc7cf96a3b410dfa7ec20a32378f4ec10b

**Steps to reproduce the behavior:**

Enable ``profileMode`` with a configuration such as (``config.toml``):

```toml
[params.profileMode]
    enabled = true
    title = "A Site Title"
    subtitle = "A subtitle"
    imageUrl= "/an-image.png"
    imageTitle = "An image alt text"
    imageWidth = 512
    imageHeight = 300
```
In (new) Edge, use 'developer tools' and notice the warning that /an-image.png is preloaded but not used within x seconds.

So, this does add the imageURL to the home page, unfortunately it also results in imageURL being preloaded on every page.

**Expected behavior**:
Image should only be preloaded on home page (where it used).
