### ISSUE TITLE
How can I change the font of post?

### ISSUE THREAD

**Issue by BytePrince** [adityatelange/hugo-PaperMod#501]
I have read the **FAQs** but I still have no idea. I have tried to modify each css which including the configuration of the font,but it didn't work.

**Comment by danielfdickinson** [comment]
All I did was create a ``assets/css/extended/custom-font.css`` file in which I have (which is more than you need, and I will be updating for modern CSS):

```css
@media not speech {
    body {
        font-size: 16px;
    }
}

@media screen and (min-width: 28em) {
    body {
        font-size: 17px;
    }
}

@media screen and (min-width: 36em) {
    body {
        font-size: 18px;
    }
}

@media screen and (min-width: 48em) {
    body {
        font-size: 19px;
    }
}

@media screen and (min-width: 56em) {
    body {
        font-size: 20px;
    }
}

@media screen and (min-width: 64em) {
    body {
        font-size: 21px;
    }
}

.entry-footer,
.footer,
.post-meta {
    font-size: .8em;
}

#menu a,
.pagination a {
    font-size: .9em;
}

.logo a {
    font-size: 1.6em;
}

.archive-meta,
.entry-content,
.page-content,
.page-footnote {
    font-size: .9em;
}
```
HTH.

Also, in future this type of request belongs in 'Discussions' rather than an issue.
