### ISSUE TITLE
[BUG] img icon in header only renders on landing page

### ISSUE THREAD

**Issue by LeonardAukea** [adityatelange/hugo-PaperMod#622]
Assume that you reference an image icon in `config.yaml` like so: 

```yaml 
  label:
    text: home
    icon: img/logo-icon.svg
    iconHeight: 35
```

It will only render on the landing page as relativeURL's are not used in the `header.html` partial: 

https://github.com/adityatelange/hugo-PaperMod/blob/3bcafa0be9461124fcd2a09a58799e2fd1e7a505/layouts/partials/header.html#L49-L50 

Therefore, you will end up looking for the file in the wrong location if you are on another site, as an example: 

`GET http://localhost:1313/posts/test/img/logo-icon.svg 404 (Not Found)`
