### ISSUE TITLE
Adding "original from..." or "translated from..."

### ISSUE THREAD

**Issue by daviddavo** [adityatelange/hugo-PaperMod#678]
I have a bilingual personal blog where I would use this in two occasions:
- When I import a personal blog post from another site. (For example, I wrote a post on example.com, but I want to include it in my website, word by word. I'd add an 'Original in example.com by `<author_name>`'). If the author_name is the same as the post author name, it could be omitted.
- When I want to publish some translated content, but the content I translated it from is not on my website. In that case, I would add something like 'Translated from example.com...' or 'Original in `<lang>` at example.com by `<author_name>`)

I already have a working example, but I'd like to ask for things to consider before making a PR

### Screen cap
![image](https://user-images.githubusercontent.com/10263941/146639608-c4d67af2-18b1-43ab-83f5-ea70734c528e.png)

### Partial template
```
{{- if .Params.original }}
{{- if or .Params.author $.Site.Params.author (.Param "ShowReadingTime") (not .Date.IsZero) }}&nbsp;|&nbsp;{{- end -}}
{{- end }}
<span>
    {{- i18n "original_from" | default "Original from" }}
    <a href="{{- .Params.original.link }}">
        {{- .Params.original.site }}
    </a>
    {{- if .Params.original.author }}
        {{- printf (i18n "original_by" | default "by %s") (.Params.original.author)}}
    {{- end}}
</span>
```

### Markdown post header
```
---
title: "Just Get My Data: Accede a tus datos de distintos servicios web"
date: 2021-01-09T11:50:13+01:00
author: David Davó
original:
    site: LiGNUx.com
    author: Mi Menda
    link: https://lignux.com/justgetmydata-accede-a-tus-datos-de-distintos-servicios-web
draft: true
---
```
