### ISSUE TITLE
Multilingual Tags page

### ISSUE THREAD

**Issue by adrienooms** [adityatelange/hugo-PaperMod#73]
Hi,

Thank you for the great theme! I am now using it for my personal blog.
I am only starting to get familiar with Hugo and I am still struggling to see where all of the information is stored and how the pages are generated.

Here's a very minor feature request: I am writing in French and English and I would like to translate the word "Tags" on the tags page (not only on the link top right of the page which I can do in the config file). I guess this could be implemented via an entry in the i18n files?

See here:

https://adrienooms.be/fr/tags/

I would like to be able to translate the word "Tags"

Thank you,

Adrien

**Comment by adityatelange** [comment]
Refer https://gohugo.io/content-management/multilingual/#taxonomies-and-blackfriday

```yml
Taxonomies:
  tag: tags
blackfriday:
  angledQuotes: true
  hrefTargetBlank: true
languages:
  en:
    blackfriday:
      angledQuotes: false
    title: English
    weight: 1
  fr:
    Taxonomies:    <---
      tag: marque   <---
    title: Français
    weight: 2
```
