### ISSUE TITLE
Order Profile Buttons

### ISSUE THREAD

**Issue by SuperMaZingCoder** [adityatelange/hugo-PaperMod#75]
Hi,

I love the theme! I was wondering if it is possible to order the buttons on the profile page? 

Currently, my config file uses the following settings for the buttons.

```toml
[params.profileMode.buttons]

    [params.profileMode.buttons.posts]
    name = "Posts"
    url = "/posts/"
    weight = 1

    [params.profileMode.buttons.archive]
    name = "Archive"
    url = "/archives/"
    weight = 2

    [params.profileMode.buttons.tags]
    name = "Tags"
    url = "/tags/"
    weight = 3

    [params.profileMode.buttons.about]
    name = "About"
    url = "/about/"
    weight = 4
```

But, the weight setting does not affect the placement of the buttons. They seem to be sorted alphabetically.

![image](https://user-images.githubusercontent.com/55718659/99198320-e578a000-2765-11eb-898c-9f7073b34aba.png)

Is there any way to order them? Thanks!

**Comment by adityatelange** [comment]
It should work not according to weights but by order they are placed in config
Try syntax below:

```toml
[params.profileMode]
title = "John Doe"
subtitle = "Programmer | Hacker | Developer"

  [[params.profileMode.buttons]]
  name = "Posts"
  url = "/posts/"

  [[params.profileMode.buttons]]
  name = "Archive"
  url = "/archive/"
```


Outout:

![image](https://user-images.githubusercontent.com/21258296/99209542-69c03700-27e9-11eb-8088-d4528a5c51e9.png)
