### ISSUE TITLE
[BUG] On iOS mobile phone, the code block font size is not the same

### ISSUE THREAD

**Issue by DejavuMoe** [adityatelange/hugo-PaperMod#828]
**Describe the bug**

 - Device/Os: iPhone 13/iOS 15.3.1
 - Type: Mobile
 - Browser and version: Safari & Google Chrome v99.0.4844.59
 - Hugo Version: 0.93.3
 - Theme Version: `80928d9f2327809b7ecccf36930e4b726a7d10b2`

**Steps to reproduce the behavior:**

1. Open Safari or Chrome browser
2. Visit my website at  www.dejavu.moe  (using the awesome PaperMod, thanks for your work)
3. Open any post with a long block of code ( [example 1](https://www.dejavu.moe/posts/hello-world/), [example 2](https://www.dejavu.moe/posts/canokey-openpgp/) )
4. find that the font size of the code is not consistent, some are very large, some are small

**Expected behavior**:

Access to the code block font size on mobile devices (cell phones) browsers remains essentially the same size

**Screenshots**
![IMG_1501](https://user-images.githubusercontent.com/57177121/158043155-7ab485d3-f9e2-4ccc-980e-0155bbe13278.PNG)
![IMG_1502](https://user-images.githubusercontent.com/57177121/158043171-47a40bde-61e3-4a64-a948-e065eba4841b.PNG)

**Additional context**

I'm not sure if it's the same problem as #695
>The issue does not repeat on another iPad Pro 11 with iPadOS 15.3.1 

My Hugo `config.yml`:

```yaml
assets:
    disableHLJS: true

markup:
    highlight:
        #anchorLineNos: true
        codeFences: true 
        guessSyntax: false 
        lineNos: false 
        noClasses: false 
        style: dracula
```

code highlighting css:

![image](https://user-images.githubusercontent.com/57177121/158043297-bc357a50-162a-4f7b-b785-b72ad97e1264.png)

**Comment by DejavuMoe** [comment]
I don't have a macbook so it's hard for me to connect my phone via USB cable for web debugging, but I found a project [remotedebug-ios-webkit-adapter](https://github.com/chrisandrewca/remotedebug-ios-webkit-adapter) that should allow remote debugging of web pages on mobile phones in Windows OS

**Temporary workaround :**

Once I stopped using `Hugo's syntax highlighter Chroma`:

```yaml
params:
    assets:
        disableHLJS: true
```
and fallback code block highlighted as default configuration:

```yaml
markup:
   # highlight:
   # anchorLineNos: true
   # codeFences: true
   # guessSyntax: true
   # lineNos: true
   # noClasses: false
   # style: monokai
```

Screenshots:

![IMG_1522](https://user-images.githubusercontent.com/57177121/158158323-1b3bbf85-c174-48fb-ac64-587e8322c3c4.PNG)
![IMG_1523](https://user-images.githubusercontent.com/57177121/158158343-80b8cd3d-3886-428d-a954-c860aa9275f7.PNG)
