### ISSUE TITLE
[BUG] False positive results in search

### ISSUE THREAD

**Issue by RoneoOrg** [adityatelange/hugo-PaperMod#863]
**Describe the bug**

Some results appear while searching "moon" (for example) with the [search form of the demo](https://adityatelange.github.io/hugo-PaperMod/search/), even if this word does not appear on the listed pages.

**Steps to reproduce the behavior:**

1. Go to the [search page of the demo](https://adityatelange.github.io/hugo-PaperMod/search/)
2. Search for "moon", or "today" for example
3. Results appear

**Expected behavior**:

No result should appear

**Comment by adityatelange** [comment]
Checkout https://fusejs.io/api/options.html#threshold

set it to `0` that won't happen 
https://github.com/adityatelange/hugo-PaperMod/blob/363756ffeeeb0fbd01e01696e278bc592e1049c1/assets/js/fastsearch.js#L39

**Comment by RoneoOrg** [comment]
Fixed with your guidance, thanks!

Note that using the settings in `config.yml` do not work:

```
params:
    fuseOpts:
         isCaseSensitive: false
         shouldSort: true
         location: 0
         distance: 1000
         threshold: 0
```

i.e the threshold is still `0.4` until I edit `fastsearch.js`
