### ISSUE TITLE
Support for i18n taxonomy

### ISSUE THREAD

**Issue by Wirone** [adityatelange/hugo-PaperMod#876]
First of all I would like to thank you for your work, I've just switched to this theme and it's great 👍 

I wanted theme that supports i18n taxonomies in URLs. With config like

```toml
# config/languages.toml

[pl]
  [pl.taxonomies]
    category = "kategorie"
    tag = "tagi"
    series = "serie"

[en]
  [en.taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"
```

this theme does this, almost. List of taxonomies work as intended and series, categories and tags are displayed in proper language. But I found that listing tags in single view does not work. I had to override `_default/single.html` layout and change code responsible for tags to this:

```go
{{ $tagsTaxonomy := $.Site.Language.Params.Taxonomies.tag }}
{{- if (index .Params $tagsTaxonomy) }}
  <ul class="post-tags">
    {{- range ($.GetTerms $tagsTaxonomy) }}
    <li><a href="{{ .Permalink }}">{{ .LinkTitle }}</a></li>
    {{- end }}
  </ul>
{{- end }}
```

It's because in front matter translated taxonomies have to be used to work with taxonomy lists, so for `en` I have `tags = ["foo"]` and for `pl` I have `tagi = ["bar"]`. I wanted to make PR with this but I thought it would be better to report issue because maybe you would like to implement it differently (also: I don't know if it would work with regular config, without translated taxonomies).
