### ISSUE TITLE
[documentation / wiki] Fix explanation how to add favicons

### ISSUE THREAD

**Issue by gkzz** [adityatelange/hugo-PaperMod#898]
## Expected

```
params:
  assets:
    favicon: "<link / absolute url>"
    favicon16x16:  "<link / absolute url>"
    favicon32x32:  "<link / absolute url>"
    apple_touch_icon:  "<link / absolute url>"
    safari_pinned_tab:  "<link / absolute url>"
```
## Actual (To be improved)

- The following `assets` directive is not correct due to wrong location. 
- The correct location is in the params directive

```
params:
assets:
  favicon: "<link / absolute url>"
  favicon16x16:  "<link / absolute url>"
  favicon32x32:  "<link / absolute url>"
  apple_touch_icon:  "<link / absolute url>"
  safari_pinned_tab:  "<link / absolute url>"
```

https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/
