### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tim-hilt** [adityatelange/hugo-PaperMod#901]
**Describe the bug**

When configuring website to use Chroma instead of Highlight.js, the syntax-highlighting disappears completely.

 - Device/Os: Arch Linux
 - Type: Desktop/Mobile
 - Browser and version: Chrome 100
 - Hugo Version: v0.98.0+extended linux/amd64
 - Theme Version: master

**Steps to reproduce the behavior:**

1. Follow [the FAQ](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#using-hugos-syntax-highlighter-chroma) to setup syntax-highlighting via Chroma
2. Observe syntax-highlighting of code-snippet in served website

**Expected behavior**:

Code-snippet is correctly highlighted

**Screenshots**

No highlighting applied

![image](https://user-images.githubusercontent.com/16037579/166468878-13c02de1-98ca-4009-9278-e8f475f1494c.png)

**Additional context**

here's the relevant excerpt from my `config.yaml`:

``` yaml
params:
  # ...
  assets:
    disableHLJS: true
# ...
markup:
  highlight:
    noClasses: false
    codeFences: true
    style: monokai
```
