### ISSUE TITLE
[BUG] Breadcrumbs item.name is empty , invalid URL in field Id

### ISSUE THREAD

**Issue by b3nsh4** [adityatelange/hugo-PaperMod#903]
Google search console shows this issue with my page `/misc` 
![image](https://user-images.githubusercontent.com/22962287/167087703-40ca46b9-e0c0-4282-b57f-4348f0ca9ccb.png)

So, i've inspected the page and found the issue that `name` has no key

```
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position":  1 ,
      "name": "",
      "item": "/misc/"
    }
  ]
}
```

My `config.toml` is below
```
menu:
  main:
    - name: about
      title: blog.b3nsh4
      url: about/
      weight: -120

    - name: blog
      title: blog.b3nsh4
      url: blog/
      weight: -120
    
    - name: projects
      url: projects/
      weight: 110

    - name: rss
      url: /index.xml
      weight: 120
    
    - name: misc
      url: misc/
      weight: 120
```

my `/misc` page is inside `content/misc/index.html` with below content
```
---
showtoc: true
tocopen: true
---
# first content
content foo bar
# content again
foo bar
```
Just want to know whether this is a bug. I've searched through issue and could not find similar. If it's any error from my side, sorry in advance.
Regards,
Ben

**Comment by adityatelange** [comment]
@b3nsh4 can you compare the config with example site source? Check if something is missing. Maube baseurl?

**Comment by b3nsh4** [comment]
> @b3nsh4 can you compare the config with example site source? Check if something is missing. Maube baseurl?

baseurl: 'https://b3nsh4.com/'

**Comment by b3nsh4** [comment]
```
baseURL: 'https://b3nsh4.com/'
languageCode: en-us
title: b3nsh4
theme: PaperMod
params:
    env: "production"
    profileMode:
        enabled: true
        title: " "
        profileMode.title: "XXX | XXX XXX"
        subtitle: "👋 ."
    socialIcons:
      - name: twitter
        url: "https://twitter.com/XXX"
      - name: github
        url: "https://github.com/XXX"
      - name: youtube
        url: "https://www.youtube.com/channel/XXX"
      - name: youtube
        url: "https://www.youtube.com/channel/XXX"
        # - name: rss
        #   url: /index.xml
    
    defaultTheme: false
    hideFooter: true
    description: "b3nsh4 website | @XXX | Ben Shaji"
    # author: 'Ben Shaji'
    comments: false


menu:
  main:
    - name: about
      title: about
      url: about/
      weight: -120

    - name: blog
      title: blog
      url: blog/
      weight: -120
    
    - name: projects
      title: projects
      url: projects/
      weight: 110

    - name: rss
      url: /index.xml
      weight: 120
    
    - name: misc
      title: misc
      url: misc/
      weight: 120
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
```
