### ISSUE TITLE
[BUG] Incorrect codeblock margin when lineNos is true

### ISSUE THREAD

**Issue by JoJoJotarou** [adityatelange/hugo-PaperMod#919]
**Describe the bug**

 - Device/Os: [e.g. Android 10] Windows 11
 - Type: [e.g. Desktop/Mobile] Desktop
 - Browser and version [e.g. Chrome 86.0]: Microsoft Edge 101.0.1210.47
 - Hugo Version [ >=0.83.0 expected]: 0.95
 - Theme Version [e.g. v4.0, master, or commit-id ]: master

**Steps to reproduce the behavior:**

1. config.yml

```yml
params:
    assets:
      disableHLJS: true
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: nord
```

2. something like this

![111](https://img1.imgtp.com/2022/05/18/NaWCMPqm.png)

**Expected behavior**:

like this

![222](https://img1.imgtp.com/2022/05/18/dQ0AKgfJ.png)

**Screenshots**

You can see the difference.

![333](https://img1.imgtp.com/2022/05/18/oCUEddmm.png)

**Additional context**

I see the browser default style of `<pre>`

```css
pre {
    display: block;
    font-family: monospace;
    white-space: pre;
    margin: 1em 0px;
}
```

So this is my solution, I'm not very web savvy, so I didn't mention PR.

```css
.post-content .highlight {
    margin: 1em 0px;
}
```
