### ISSUE TITLE
Does the responsive cover images feature use q100? 

### ISSUE THREAD

**Issue by singhkays** [adityatelange/hugo-PaperMod#92]
@Kartoffel Thank you for implementing the responsive cover images feature here https://github.com/adityatelange/hugo-PaperMod/pull/43/files. 

If I read line https://github.com/adityatelange/hugo-PaperMod/pull/43/files#diff-dd30a18c966d1e96b055d5c9955d9d8ef1200159705fb5a6323ceb4a89db5be7R14 correctly, does this mean this uses q100 by default and does not respect the imaging quality options set in the config.yml or toml file? If so, q100 is producing files that are larger than the source file in my case for cover image and following expected q80 for the following figure shortcode https://cpbotha.net/2020/05/02/drop-in-replacement-for-hugo-figure-shortcode-with-responsive-img-srcset/ 

**Hopefully the image annotation explains this** 
![Xnip2020-11-28_15-30-31](https://user-images.githubusercontent.com/6164178/100528231-3e492f00-318f-11eb-83db-5aabc1c6b044.jpg)

**Here's my config.yml file**
```yaml
imaging:
  # Default resample filter used for resizing. Default is Box,
  # a simple and fast averaging filter appropriate for downscaling.
  # See https://github.com/disintegration/imaging
  resampleFilter: "lanczos"

  # Default JPEG quality setting. Default is 75.
  quality: 80
```
