### ISSUE TITLE
Feature doc's description for search not fully written.

### ISSUE THREAD

**Issue by nolleh** [adityatelange/hugo-PaperMod#947]
in the feature description, 
https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page

that says 
```yml
# 1. config.yml, add outputs option
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

..

# 2. make search content file 
---
title: "Search" # in any language you want
layout: "search" # is necessary
# url: "/archive"
# description: "Description for Search"
summary: "search"
placeholder: "placeholder text in search input box"
---
```

but actually, also need to add 'search menu', like below. 
```yml
menu:
  main:
    - identifier: categories.. 
    # - ..
    - identifier: search
      name: Search
      url: /search/
      weight: 20
```

if you don't put that on config, then the search menu doesn't showed up.

(I think, the opened issues about search doesn't working, can be related with this)
